### PR TITLE
Moved to solution 4, added loop count

### PR DESCRIPTION
**Pull request by rmasci**
## Contributing requirements

* [x ] I read the contribution guidelines in CONTRIBUTING.md.
* [ x] I placed my solution in the correct solution folder.
* [ x] I added a README.md with the right badge(s).
* [ x] I added a Dockerfile that builds and runs my solution.
* [ x] I selected `drag-race` as the target branch.
* [ x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Could you indicate why this should be a new solution instead of an improvement on solution_3?

**Comment by rmasci** [comment]
> Could you indicate why this should be a new solution instead of an improvement on solution_3?

I wrote solution_4 before solution_3.  I submitted it originally as solution_3, that pull request was rejected because another had submitted a pull request that I wasn't aware of -- that today is solution_3. So I pulled my version, made it solution_4. I didn't build off of solution_3 at all, and the way I've implemented goroutines is a lot different.

Since the submission I've further 'tweaked' the program so that I can limit the number of CPUs and by default it's 1. It also shows the number of go routines -- it's a bit more interesting as you can see when the 'Stop' is issued, and the go routines filtering down.  This solution runs faster than solution 1 and 2, while still only using 1 cpu. When you open it up to all cpus on my system it runs faster than solution_3 -- but again is different in that when one go routine ends, it starts another, and tries to keep a number of them running at all times -- which can be shown in a version I've not uploaded yet.

**Comment by rbergen** [comment]
The PR that was merged was #367, which was open before you opened #378, meaning you could have been aware of it if you had looked at the list of open PRs. If I had seen your original PR when #367 was merged then I would have told you to discuss how to integrate your proposed changes into that PR. With that PR now merged, the goal should be improving its performance, rather than moving towards adding a new solution.

**Comment by marghidanu** [comment]
Please tick the checkboxes using [x] without spaces in between. More info here: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

**Comment by rbergen** [comment]
@rmasci Just to clarify my previous comment: I will not move towards merging this as a new solution unless the scenario of improving solution_3 has been exhausted as a possibility.

**Comment by rbergen** [comment]
Closing for reason indicated. If desired, it can be reopened with my previous comment in mind.

**Pull request closed without merging**
