### PR TITLE
Dockerfile lint

### PR DESCRIPTION
**Pull request by marghidanu**
This one has been sitting for a few days as I was testing it out. This PR introduces various checks for the Dockerfile using Hadolint to make sure we have good practices. Additionally, it changes how the build matrix runs by correctly marking the failed jobs and not stopping the pipeline at the first fail.

### CODE REVIEW

**Comment by rbergen** [comment]
I guess we should make addressing the issues in existing Dockerfiles a maintainer action after merging this?

**Comment by marghidanu** [comment]
Yes, that’s the idea. Since we have CI might as well use it :)

**Review by rbergen — APPROVED** [review]
Alight then, let's do this! :)

**Comment by marghidanu** [comment]
Maybe I should add a build status badge to the README?

**Comment by rbergen** [comment]
I think that might be a good idea, in fact regardless of this PR.

I'm going to merge this after I submit this comment. Let's try to fix the 10 issues that are now known because of it, quickly. I really don't like big red Xs :)

**Pull request merged**
