### PR TITLE
Tweak Nim solution_3 performance...

### PR DESCRIPTION
**Pull request by GordonBGood**
## Description

As per the main competitor, Rust solution_1 "unrolled hybrid", this change increases the threshold for the dense prime values to 129 from 63 for a slight increase in performance that should put it at about the same level as the top Rust solution.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@GordonBGood This PR causes a merge conflict. I'm guessing the PR is based on a branch off a commit before the last PR on PrimeNim/solution_3 was merged.

**Comment by GordonBGood** [comment]
@rbergen:

> @GordonBGood This PR causes a merge conflict. I'm guessing the PR is based on a branch off a commit before the last PR on PrimeNim/solution_3 was merged.

Yes, that's exactly what happened, I forgot to load the upstread base before the new branch.

What's the best way to fix it?  Close the PR, update the base, then resubmit?

**Comment by mike-barber** [comment]
@GordonBGood I think you should be able to merge latest base into your branch, and resolve the merge conflicts locally. This should make this problem go away without needing to create a new PR. 

Probably something like this:
`git checkout drag-race`
`git pull upstream drag-race` -- to get the latest from the upstream repo
`git checkout <your branch>`
`git merge drag-race` -- to update your PR branch with latest drag-race, and resolve any merge conflicts locally 

If it's all resolved locally, you should be able to just push to update this PR and all should be good. Hopefully :)

Take a backup of your code first though :)

**Comment by Macleykun** [comment]
> @GordonBGood I think you should be able to merge latest base into your branch, and resolve the merge conflicts locally. This should make this problem go away without needing to create a new PR.
> 
> Probably something like this:
> `git checkout drag-race`
> `git pull upstream drag-race` -- to get the latest from the upstream repo
> `git checkout <your branch>`
> `git merge drag-race` -- to update your PR branch with latest drag-race, and resolve any merge conflicts locally
> 
> If it's all resolved locally, you should be able to just push to update this PR and all should be good. Hopefully :)
> 
> Take a backup of your code first though :)

Out of curiousity i tested this by cloning GordonBGood's repo. Great steps! If you want them for your usecase you can use these:
(note, i'm still a newbie in git, so double check if this indeed the right way)
(given you are with bash/git in your project folder)
```
git checkout drag-race
git remote add upstream https://github.com/PlummersSoftwareLLC/Primes.git (i had to do this extra)
git pull upstream drag-race
git checkout GordonBGood-nim-tweak
(Now you'll go and fix the two files :))
git add . (to mark resolution followed)
git commit -am "Merged with upstream" (not sure why i always use -am, instead of -m now i think of it)
git merge drag-race
```
Sorry to randomly pass by :P

**Comment by GordonBGood** [comment]
@rbergen, @Macleykun:

> > @GordonBGood I think you should be able to merge latest base into your branch, and resolve the merge conflicts locally. This should make this problem go away without needing to create a new PR.
> > Probably something like this:
> > `git checkout drag-race`
> > `git pull upstream drag-race` -- to get the latest from the upstream repo
> > `git checkout <your branch>`
> > `git merge drag-race` -- to update your PR branch with latest drag-race, and resolve any merge conflicts locally
> > If it's all resolved locally, you should be able to just push to update this PR and all should be good. Hopefully :)
> > Take a backup of your code first though :)

Good advice.  I have multiple backups of the project.

> Out of curiousity i tested this by cloning GordonBGood's repo. Great steps! If you want them for your usecase you can use these:
> (note, i'm still a newbie in git, so double check if this indeed the right way)
> (given you are with bash/git in your project folder)
> 
> ```
> git checkout drag-race
> git remote add upstream https://github.com/PlummersSoftwareLLC/Primes.git (i had to do this extra)

Yes, when I tried rbergen's steps, this was the hang-up and the thing that was missing.

> git pull upstream drag-race
> git checkout GordonBGood-nim-tweak
> (Now you'll go and fix the two files :))
> git add . (to mark resolution followed)
> git commit -am "Merged with upstream" (not sure why i always use -am, instead of -m now i think of it)
> git merge drag-race
> ```

I think these are good steps, but after the hang-up, I just ended up using the GitHub integration is Visual Studio Code (VSCode) which is my favorite editor.  With it, doing this was almost automatic with a few clicks once I figured out what I had to do.

> Sorry to randomly pass by :P

No problem, thanks for the help.

**Comment by rbergen** [comment]
@mike-barber and @Macleykun Thanks for your help with addressing this.

**Pull request merged**
