### PR TITLE
CPP with inlined amd64 assembler

### PR DESCRIPTION
**Pull request by hildenborg**
## Description
Multithreaded CPP with inlined amd64 assembler.
I chosed to put it in it's own folder as it is neither fully C++ or fully assembler.

## Contributing requirements
* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@hildenborg As you describe it this is a mixed language solution, for which the PrimeMixed directory already exists. This solution would then become the one in directory PrimeMixed/solution_5.

**Comment by hildenborg** [comment]
I didn't see the mixed language category. Moved into the correct place now.

**Review by rbergen — APPROVED** [review]
> I didn't see the mixed language category. Moved into the correct place now.

Not a problem, one of the reasons I'm here. :) 

I took the liberty of setting the execute bit on run.sh, without which the solution wouldn't run. With that, it LGTM.

As this is a new solution in a new mix of languages, I will ask for a second review from @marghidanu also.

**Comment by rbergen** [comment]
Merging based on "he who is silent agrees".

**Pull request merged**
