### PR TITLE
Forth solution

### PR DESCRIPTION
**Pull request by tjol**
## Description

I thought I'd do another relatively obscure language that I know little about.

I've marked it as “faithful” as the memory is reallocated and reinitialized every time, even though there are no classes or structs.

There are some extra spaces in the output – I hope these are ok. If not, I should be able to get rid of them with a bit of effort.

(It's slower than I thought it would be!)

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
I'll gladly add this new member to the collection of Primes languages, but I will have to insist that it is marked as unfaithful for the reason you have yourself indicated. And I do that acknowledging fully that this is due to limitations that are intrinsic to the language.

**Comment by tjol** [comment]
Absolutely. That's why I pointed it out!

**Review by rbergen — APPROVED** [review]
LGTM. I've verified that the auxiliary spaces in the output don't prevent its parsing by the benchmark tool.

**Comment by rbergen** [comment]
Still works on my machine

**Pull request merged**
