### PR TITLE
Crystal optimizations

### PR DESCRIPTION
**Pull request by marghidanu**
## Description

* Switched to `BitArray` instead of `Array(Bool)`.
* Updated benchmark numbers
* Code cleanup

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct category folder.
* [x] I added a README.md or Dockerfile.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by mike-barber** [comment]
Hi Tudor

I gave the Docker one a few runs on my Ryzen 3900X, and it's pretty fast: 
```
Passes: 9019 Time: 5.000000 Avg: 0.000554 Limit: 1000000 Count1: 78498 Count2: 78498 Valid: true
Passes: 9179 Time: 5.000000 Avg: 0.000545 Limit: 1000000 Count1: 78498 Count2: 78498 Valid: true
Passes: 9640 Time: 5.000000 Avg: 0.000519 Limit: 1000000 Count1: 78498 Count2: 78498 Valid: true
Passes: 9669 Time: 5.000000 Avg: 0.000517 Limit: 1000000 Count1: 78498 Count2: 78498 Valid: true
Passes: 9156 Time: 5.000000 Avg: 0.000546 Limit: 1000000 Count1: 78498 Count2: 78498 Valid: true
Passes: 9075 Time: 5.000000 Avg: 0.000551 Limit: 1000000 Count1: 78498 Count2: 78498 Valid: true
Passes: 9167 Time: 5.000000 Avg: 0.000545 Limit: 1000000 Count1: 78498 Count2: 78498 Valid: true
```

**Comment by marghidanu** [comment]
Wow, super-nice, thanks a lot @mike-barber. My machines are all pretty slow apparently. :)

**Comment by mike-barber** [comment]
Weirdly it's faster under Docker/alpine... it's only around 8000 using run.sh. Different c runtime I guess. 

Ryzen 3900X is a monster, but I'd expect the M1 to get closer or outpace it. It all depends on the compiler support though; Crystal might not be using a version of LLVM that knows about it. Or there might just be some compilation flags we need. 

Rust also uses LLVM, and I've enabled a few options:
- Target "native" cpu (i.e. whatever the machine is using): https://github.com/davepl/Primes/blob/drag-race/PrimeRust/solution_1/.cargo/config
- Enabled link time optimisation

It might be possible to set some of LLVM options in Crystal too

**Comment by marghidanu** [comment]
In Alpine is built statically maybe that’s the reason. But this is very interesting...

**Comment by marghidanu** [comment]
Crystal still doesn't have official support for the M1 chip. I'm hoping they release a version for it soon. Until then I'm stuck with these numbers. As you can see from the benchmark in the README file, it actually performs better under Rosetta which is weird.

**Comment by rhbvkleef** [comment]
What's with the `werk.yml` file? Is that a part of a plan to fragment the CI config, or can you somehow run these files locally?

**Comment by marghidanu** [comment]
It's my local CI, more details here: https://github.com/marghidanu/werk

**Pull request merged**
