### PR TITLE
Rust implementation

### PR DESCRIPTION
**Pull request by mike-barber**
Dave, thanks for the video.

Rust seems like something you might enjoy, so I put together a basic Rust implementation based on the C++ version.

It performs quite well on my machine (Ryzen 3900X)
```
Windows C++:  Passes: 15391, Time: 10.000000, Avg: 0.000650, Limit: 1000000, Count: 78498, Valid: 1
Linux clang:  Passes: 15687, Time: 10.000000, Avg: 0.000637, Limit: 1000000, Count: 78498, Valid: 1
Windows Rust: Passes: 20542, Time: 10.000122, Avg: 0.00048681346, Limit: 1000000, Count: 78498, Valid: true
Linux Rust:   Passes: 21170, Time: 10.000431, Avg: 0.00047238692, Limit: 1000000, Count: 78498, Valid: true
```

I've added some notes in PrimeSieveRust/README.md if you're keen to play around with it a bit.

### CODE REVIEW

**Comment by Thalhammer** [comment]
@mike-barber I dont know about rust, but something feels wrong about those C++ numbers. I get almost 18000 on my Ryzen 3800X (which should have comparable simple core performance to yours). You might want to recheck the compile flags.

**Comment by davepl** [comment]
I’m only running for 5 seconds,but getting 7700 consistently with -Ofast, and even the same under Linux on the same hardware!

Cheers
Dave

**Comment by mike-barber** [comment]
@Thalhammer -- interesting! Maybe share the compiler / config you're using for C++; it'll be interesting to see which compiler you've used. Dave's results sound the same as mine, with 7.7k in 5s roughly equaling my 15.5k in 10s. Or pull the Rust project and give it a bash too :)

In my case, here's what I did for the C++ numbers:
- for Windows, I just opened the solution in Visual Studio and ran in Release / x64 with the configuration as pulled from the repo; didn't change any of the flags.
- for Linux, I'm not doing anything interesting: just `clang++ -O3` or `g++ -O3` both yielding around the same 15.5k
- there's a small performance bump to 16k if I target my cpu with `clang++ -march=znver2 -O3`

I am running the Linux workloads under WSL2, but there's generally only a very small performance impact from doing this -- less than going from 18k to 15k for instance. Also bear in mind I'm not up to scratch on gcc/clang flags -- it's been a few years since I've done any C++ development on Linux.

**Comment by Thalhammer** [comment]
`g++-10 -o baseline baseline.cpp -O2 -std=c++2a`
```./baseline2
Passes: 16864, Time: 10.000000, Avg: 0.000593, Limit: 1000000, Count: 78498, Valid: 1
```

I might have had some optimizations still in when I got that 1800 run, but I get ~16800 consistent with the stock version in the repo at the time of the pull request.
```
Architektur:                   x86_64
CPU Operationsmodus:           32-bit, 64-bit
Byte-Reihenfolge:              Little Endian
CPU(s):                        16
Liste der Online-CPU(s):       0-15
Thread(s) pro Kern:            2
Kern(e) pro Socket:            8
Sockel:                        1
NUMA-Knoten:                   1
Anbieterkennung:               AuthenticAMD
Prozessorfamilie:              23
Modell:                        113
Modellname:                    AMD Ryzen 7 3800X 8-Core Processor
Stepping:                      0
CPU MHz:                       2199.805
Maximale Taktfrequenz der CPU: 3900,0000
Minimale Taktfrequenz der CPU: 2200,0000
BogoMIPS:                      7799.85
Virtualisierung:               AMD-V
L1d Cache:                     32K
L1i Cache:                     32K
L2 Cache:                      512K
L3 Cache:                      16384K
NUMA-Knoten0 CPU(s):           0-15
Markierungen:                  fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
```

Note that pretty much everything except O2 gives worse results, but this seems to be highly compile dependent.
Clang with O2 only gives me around 12000 while it is on par with g++ -O2 when I use clang -O3.

**Comment by dasper** [comment]
I also have a 3900x and am getting similar results

C++ using `run.sh`
- 10 sec
`Passes: 14907, Time: 10.000000, Avg: 0.000671, Limit: 1000000, Count: 78498, Valid: 1`
- 5 sec
`Passes: 7476, Time: 5.000000, Avg: 0.000669, Limit: 1000000, Count: 78498, Valid: 1`

Rust
- 10 sec
`Passes: 19224, Time: 10.000083, Avg: 0.00052018743, Limit: 1000000, Count: 78498, Valid: true`
- 5 sec
`Passes: 9469, Time: 5.000305, Avg: 0.0005280711, Limit: 1000000, Count: 78498, Valid: true`

Note: I am not bothering thinning out running processes on my development machine and do have quite a few things running (Goland, Rider, Azure Data Studio, Vivaldi, etc)

**Comment by mike-barber** [comment]
Thanks @Thalhammer -- it looks like gcc 10 is a little faster than the gcc 9 I was using. On my machine, using your flags and gcc 10, I'm getting pretty close to your value of 16864:
```
Passes: 16180, Time: 10.000000, Avg: 0.000618, Limit: 1000000, Count: 78498, Valid: 1
```
This is close enough that it's probably explainable by WSL2. And like @dasper (thanks for your results too!) I've also got a few things running. Not least of all just Windows 10 :)

**Comment by botahamec** [comment]
Please don't include `Cargo.lock`. It will be recreated by Cargo when the project is built

**Comment by mike-barber** [comment]
> Please don't include `Cargo.lock`. It will be recreated by Cargo when the project is built

Thanks @botahamec, although I'm not so sure: I'm following the advice given in the Rust book, as this is a binary project rather than a library: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html. It seems like a good idea particularly for a benchmark, for reproducibility.
> If you’re building a non-end product, such as a rust library that other rust packages will depend on, put Cargo.lock in your .gitignore. If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or cdylib, check Cargo.lock into git. 

Let me know if you agree.

**Comment by mike-barber** [comment]
Hi @davepl -- thanks for the Raspi vs M1 vs ThreadRipper video; was looking forward to that one!

I've updated this PR with a second Rust implementation that permits either bits or bytes (1/0) for storage, similar to the `vector<bool>` approach you mentioned. I've noted all the new performance results in `PrimeSieveRust/README.md`. 

A couple of interesting things

## bits vs bytes
Using simple bytes is a lot faster -- I'm getting ~33k for bytes vs the ~22k for flipping bits on the Ryzen. 
```
Bit storage:   Passes: 22392, Time: 10.000229, Avg: 0.00044659828, Limit: 1000000, Count: 78498, Valid: true
Byte storage:  Passes: 33980, Time: 10.000248, Avg: 0.00029429805, Limit: 1000000, Count: 78498, Valid: true
```

## Raspberry Pi
It's actually *really* fast on my Raspberry Pi 4 too:
```
Bit storage:   Passes: 4862, Time: 10.000785, Avg: 0.0020569281, Limit: 1000000, Count: 78498, Valid: true
Byte storage:  Passes: 5041, Time: 10.001149, Avg: 0.0019839613, Limit: 1000000, Count: 78498, Valid: true
```
I'm guessing we've got a memory bandwidth limit on the Pi. Or it's super fast at flipping bits: I haven't had a look at the assembly code yet. One thing it does hint at: there's a bit more we can squeeze out of the Pi on the C++ side.



Please let me know if you'd like me to refactor stuff to make it clearer or more fair. Happy to help polish it if you decide you'd like it merged into your codebase. 

Thanks
Mike

**Comment by mike-barber** [comment]
Resolved `.gitignore` merge conflict and added a convenient `run.sh` script to run both variants

**Comment by botahamec** [comment]
Similar results on my Ryzen 3600 (Who's going to complete the series with a Ryzen 3? 😛)

**simple-bits:**
```
Passes: 19782, Time: 10.0004015, Avg: 0.00050553033, Limit: 1000000, Count: 78498, Valid: true
```

**abstracted:**
```
Bit storage:   Passes: 21629, Time: 10.000025, Avg: 0.00046234336, Limit: 1000000, Count: 78498, Valid: true
Byte storage:  Passes: 33127, Time: 10.000243, Avg: 0.0003018759, Limit: 1000000, Count: 78498, Valid: true
```

I checked the simple-bits binary to confirm that it's similar to the C++ version. I did think the `count_primes` function was questionable, but changing it to a loop doesn't change the performance. I'll try it on my Raspberry Pi 4 later.

**Comment by mike-barber** [comment]
@botahamec thanks for checking the results!

I didn't do much to the `count_primes` function, and left the "find next factor" bit alone too. They could be faster, but I did find that the only really hot code path is setting bits/bytes to zero so there wouldn't have been much benefit; so just went for readability for those ;)

When testing on the Pi, if you don't have some heatsinking, it might be a good idea to throw a `sleep` in there for a few seconds between the bits and bytes runs to let the thing cool off a bit. It heats up fast and goes into thermal throttling otherwise.

**Comment by botahamec** [comment]
My results were different on the Raspberry Pi 4. I have a fan and heatsinks, so I don't think it thermal throttled. I ran it on Manjaro ARM, not overclocked or anything

```
Bit storage: 4156 passes
Byte storage: 4146 passes
Simple bits: 4388 passes
```

**Comment by mike-barber** [comment]
Super, thanks! That sounds roughly in the same ballpark. Still nice and quick for a pi :) Mine is a little overclocked, but I can't remember by how much - I'll check it out tomorrow. Are you using a 64 bit build?

**Comment by mike-barber** [comment]
@botahamec it looks like it was down to the overclock on the Pi -- I was at 1.8 GHz instead of the stock 1.5 GHz, so 20% over. With stock clocks, I'm getting very similar results to you. Also running over SSH without a display connected.

```
Simple bits:   Passes: 4432, Time: 10.001713, Avg: 0.0022567043, Limit: 1000000, Count: 78498, Valid: true
Bit storage:   Passes: 4186, Time: 10.001791, Avg: 0.0023893432, Limit: 1000000, Count: 78498, Valid: true
Byte storage:  Passes: 4109, Time: 10.000267, Avg: 0.002433747, Limit: 1000000, Count: 78498, Valid: true
```
It's not super consistent though. Occasionally, the byte storage run is around the 3200-3500 mark -- might be something like a memory alignment or cache line thing I guess.

**Comment by botahamec** [comment]
> It's not super consistent though. Occasionally, the byte storage run is around the 3200-3500 mark -- might be something like a memory alignment or cache line thing I guess.

I got that too, usually when the terminal window wasn't in focus

**Comment by botahamec** [comment]
> Super, thanks! That sounds roughly in the same ballpark. Still nice and quick for a pi :) Mine is a little overclocked, but I can't remember by how much - I'll check it out tomorrow. Are you using a 64 bit build?

Just saw this lol. Yeah, I'm using Manjaro specifically because it's a 64-bit OS, and I compiled with the aarch64 target

**Comment by mike-barber** [comment]
@rhbvkleef @davepl Hi Rolf and Dave -- I'd really like to get this merged :) It's one of the earlier PRs still outstanding, and I feel like it might have been missed in all the noise.

As far as I can tell, it should be good to go:
- close to the original C++ implementation, so it's at least fair
- has a pretty decent readme explaining how to install Rust and get started
- has a `run.sh` to enable easy testing
- resolved prior merge conflict with the .gitignore file

I'm happy to do any rework required -- just let me know! In particular:
- not sure if I should be aiming for a `5s` or `10s` run; or both?
- multithreaded version - not sure if it's easier to add to this PR, or open another one later?

Let me know if I can help with anything else too.

**Comment by mike-barber** [comment]
Having had a good look at the discussion in #42, it looks like Rolf has quite a workload organising everything! 

In order to help out, I have: 
- updated this PR to target the `drag-race` branch
- updated the directory structure so this goes into `PrimeRust/stl-faithful/mike-barber` instead of into the root
- updated code and results to reflect a `5s` run

@rhbvkleef, please let me know if you need any help with CI side of this too :)

**Comment by rhbvkleef** [comment]
Thanks @mike-barber :) You have indeed just made my life slightly easier :)

For now, I´ll merge this PR. It would be very useful if you could, at some point, write a `Dockerfile` that runs the implementation. I´ve noted down your name in case there´s anything I can think of that you could help with.

**Comment by mike-barber** [comment]
Thanks @rhbvkleef! I'll get Docker sorted and open a PR for that. 

I've opened #109 for Docker.

**Pull request merged**
