### PR TITLE
Add Haxe Prime Sieve

### PR DESCRIPTION
**Pull request by eth0fox**
## Description

I was unsure of the requirements when I first created the pull request (#125). This is an updated PR that merges to drag-race instead of main.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct category folder.
* [x] I added a README.md or Dockerfile.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
Would it be possible to include a Dockerfile for the implementation?

**Comment by eth0fox** [comment]
@marghidanu I’ve never used Docker so I’m not exactly sure how to

**Comment by rbergen** [comment]
Coincidentally, I was just looking into this. It turns out that Haxe is not that easy to get to run in Docker, but I did get it to work in the end. 

A file called "Dockerfile" will need to be added to the solution directory, containing the following:
```
FROM haxe:4.2.1-alpine3.13

RUN apk update && apk add --no-cache g++ python3 musl-locales bash
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h

WORKDIR /opt/app
COPY . .

RUN haxelib install hxcpp
RUN haxe cpp.hxml
RUN haxe python.hxml

COPY run.sh .
RUN chmod a+x run.sh

ENTRYPOINT [ "/opt/app/run.sh" ]
```

A small shell script needs to be added, as well. It needs to be called "run.sh" and contain the following:
```
#!/bin/bash

cd $(dirname "${BASH_SOURCE[0]}")

./bin/cpp/Main
haxe interp.hxml
python3 bin/py.py
```

**Comment by eth0fox** [comment]
I have added a Dockerfile, which *should* work. The interpreter and Python versions run, but the CPP failed to build, as I was running it on an ARM machine and Haxe generated build files for x86_64.

**Comment by marghidanu** [comment]
> I have added a Dockerfile, which _should_ work. The interpreter and Python versions run, but the CPP failed to build, as I was running it on an ARM machine and Haxe generated build files for x86_64.

Are you using an M1, or ARM CPU?

**Comment by marghidanu** [comment]
> Coincidentally, I was just looking into this. It turns out that Haxe is not that easy to get to run in Docker, but I did get it to work in the end.
> 
> A file called "Dockerfile" will need to be added to the solution directory, containing the following:
> 
> ```
> FROM haxe:4.2.1-alpine3.13
> 
> RUN apk update && apk add --no-cache g++ python3 musl-locales bash
> RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
> 
> WORKDIR /opt/app
> COPY . .
> 
> RUN haxelib install hxcpp
> RUN haxe cpp.hxml
> RUN haxe python.hxml
> 
> COPY run.sh .
> RUN chmod a+x run.sh
> 
> ENTRYPOINT [ "/opt/app/run.sh" ]
> ```
> 
> A small shell script needs to be added, as well. It needs to be called "run.sh" and contain the following:
> 
> ```
> #!/bin/bash
> 
> cd $(dirname "${BASH_SOURCE[0]}")
> 
> ./bin/cpp/Main
> haxe interp.hxml
> python3 bin/py.py
> ```

Why do you need the Bash file? You can always inline commands with `bash -c "..."`

**Comment by eth0fox** [comment]
> > I have added a Dockerfile, which _should_ work. The interpreter and Python versions run, but the CPP failed to build, as I was running it on an ARM machine and Haxe generated build files for x86_64.
> 
> Are you using an M1, or ARM CPU?

I use an M1 machine.

**Comment by rbergen** [comment]
> Why do you need the Bash file? You can always inline commands with `bash -c "..."`

"Need" is indeed the wrong word. I prefer to use a script if the run encompasses multiple commands, because I personally tend to lose oversight more quickly when using the inline command approach. One might say it's a matter of taste.

**Comment by rbergen** [comment]
LGTM. @marghidanu, I suggest we merge despite @TayIorRobinson's comment on issues on M1. That's because
1. the solution works on amd64
2. compatibility with specific architectures is not a contributing requirement
3. I already know that other merged solutions _will_ have similar issues on non-amd64 architectures.

**Pull request merged**
