### PR TITLE
Rust unrolled hybrid

### PR DESCRIPTION
**Pull request by mike-barber**
## Description

This is a Rust implementation of the unrolled-hybrid solution that @GordonBGood and I have been discussing for the last few days. I don't think it'll be as fast as his Nim version, but it's definitely faster than my existing striped-hybrid solution. It's faster than the Chapel implementation on my machine, but a bit slower than it on the little Pi. 

More details on the approach are in the README, but it should be broadly similar to Gordon's approach. I'm still setting only one bit at a time -- the masks are words with a single bit set in them. 

A couple of other housekeeping items:
- In order to support the procedural macros, I had to do a little bit of refactoring and move projects into subdirectories, etc. Luckily this is transparent on the PR.
- I had to change the trait (interface) for FlagStorage: I removed the `start` parameter as it was redundant: it's inferred from the factor, and different storage strategies approach this differently.
- Following general discussions on naming conventions, I've shortened the names I'm using for existing solutions, and I've labelled the `...blocks` algorithms with the block size.

## Contributing requirements
* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
The `blocks4k` implementations seem to be the (only) ones who do not output a "Computing primes to..." header before the actual run output. This is clearly not a blocker for approval, just an inconsistency I just noticed.

```
Computing primes to 1000000 on 1 thread for 5 seconds.
bit-striped-blocks16k Passes: 14520, Threads: 1, Time: 5.0001692772, Average: 0.0003443643, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-blocks16k;14520;5.0001692772;1;algorithm=base,faithful=yes,bits=1
bit-striped-blocks4k Passes: 13592, Threads: 1, Time: 5.0002675056, Average: 0.0003678831, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-blocks4k;13592;5.0002675056;1;algorithm=base,faithful=yes,bits=1

Computing primes to 1000000 on 1 thread for 5 seconds.
bit-striped-hybrid-blocks16k Passes: 18118, Threads: 1, Time: 5.0003833771, Average: 0.0002759898, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-hybrid-blocks16k;18118;5.0003833771;1;algorithm=base,faithful=yes,bits=1
bit-striped-hybrid-blocks4k Passes: 16478, Threads: 1, Time: 5.0003428459, Average: 0.0003034557, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-hybrid-blocks4k;16478;5.0003428459;1;algorithm=base,faithful=yes,bits=1

Computing primes to 1000000 on 1 thread for 5 seconds.
bit-unrolled-hybrid Passes: 30223, Threads: 1, Time: 5.0002398491, Average: 0.0001654449, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-unrolled-hybrid;30223;5.0002398491;1;algorithm=base,faithful=yes,bits=1

Computing primes to 1000000 on 8 threads for 5 seconds.
byte            Passes: 24642, Threads: 8, Time: 5.0011787415, Average: 0.0002029534, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_byte;24642;5.0011787415;8;algorithm=base,faithful=yes,bits=8

Computing primes to 1000000 on 8 threads for 5 seconds.
bit             Passes: 18725, Threads: 8, Time: 5.0018477440, Average: 0.0002671214, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit;18725;5.0018477440;8;algorithm=base,faithful=yes,bits=1

Computing primes to 1000000 on 8 threads for 5 seconds.
bit-rotate      Passes: 17641, Threads: 8, Time: 5.0022211075, Average: 0.0002835566, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-rotate;17641;5.0022211075;8;algorithm=base,faithful=yes,bits=1

Computing primes to 1000000 on 8 threads for 5 seconds.
bit-striped     Passes: 27973, Threads: 8, Time: 5.0013947487, Average: 0.0001787936, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped;27973;5.0013947487;8;algorithm=base,faithful=yes,bits=1

Computing primes to 1000000 on 8 threads for 5 seconds.
bit-striped-blocks16k Passes: 37352, Threads: 8, Time: 5.0005331039, Average: 0.0001338759, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-blocks16k;37352;5.0005331039;8;algorithm=base,faithful=yes,bits=1
bit-striped-blocks4k Passes: 33301, Threads: 8, Time: 5.0013113022, Average: 0.0001501850, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-blocks4k;33301;5.0013113022;8;algorithm=base,faithful=yes,bits=1

Computing primes to 1000000 on 8 threads for 5 seconds.
bit-striped-hybrid-blocks16k Passes: 49853, Threads: 8, Time: 5.0011858940, Average: 0.0001003187, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-hybrid-blocks16k;49853;5.0011858940;8;algorithm=base,faithful=yes,bits=1
bit-striped-hybrid-blocks4k Passes: 46578, Threads: 8, Time: 5.0007357597, Average: 0.0001073626, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit-striped-hybrid-blocks4k;46578;5.0007357597;8;algorithm=base,faithful=yes,bits=1
```

If you want to proceed without changing this then that's fine and you can just say so.

**Comment by mike-barber** [comment]
> The blocks4k implementations seem to be the (only) ones who do not output a "Computing primes to..." header before the actual run output. This is clearly not a blocker for approval, just an inconsistency I just noticed.

Thanks -- that's a good point! It is a bit noisy, and probably due for a bit of a refactor :) Maybe I'll print it out once for threads = 1 and threads = N.

**Comment by mike-barber** [comment]
Thanks @rbergen -- the running/reporting side of the solution has been in need of a bit of polishing for a while, so this was a good opportunity to clean it up a bit. The output is a bit easier to read now:

```
-------------------------------------------------------
Computing primes to 1000000 on 1 thread for 5 seconds.
-------------------------------------------------------

byte                           Passes: 18538, Threads: 1, Time: 5.0000286102, Passes / sec: 3707.58, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_byte;18538;5.0000286102;1;algorithm=base,faithful=yes,bits=8

bit                            Passes: 11932, Threads: 1, Time: 5.0000791550, Passes / sec: 2386.36, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit;11932;5.0000791550;1;algorithm=base,faithful=yes,bits=1

-------------------------------------------------------
Computing primes to 1000000 on 24 threads for 5 seconds.
-------------------------------------------------------

byte                           Passes: 171805, Threads: 24, Time: 5.0009479523, Passes / sec: 34354.49, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_byte;171805;5.0009479523;24;algorithm=base,faithful=yes,bits=8

bit                            Passes: 135679, Threads: 24, Time: 5.0010743141, Passes / sec: 27129.97, Limit: 1000000, Counts: 78498, Valid: Pass
mike-barber_bit;135679;5.0010743141;24;algorithm=base,faithful=yes,bits=1

```

The actual reporting lines are unchanged, and still going to `stdout`; all the other pretty stuff is to `stderr`.
I've also moved the single-threaded runner into its own simpler method: I've had a few people asking about why I'm using threads, etc... so this just makes it a lot clearer :)

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by mike-barber** [comment]
Thanks @rbergen!

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
