### PR TITLE
[Odin] First submission for the Odin programming language

### PR DESCRIPTION
**Pull request by omgitsmoe**
## Description
This is a faithful implementation of the base algorithm in [Odin](https://github.com/odin-lang/Odin) with 1- and 8-bit versions, which are run in both single- and multi-threaded modes. Originally based on the C++ version of davepl. This would be the first solution in Odin.

Odin is a system programming language, so it should probably be grouped with the likes of C, C++, Zig, etc.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
I think we'll need to use a docker base image that has Odin baked in. The docker build now takes about 3 minutes, and using a git clone means that the version of Odin that's actually used is rather fluid.

I'm also curious why the solution is marked as arch-amd64 only?

**Comment by omgitsmoe** [comment]
There is no base image with Odin included as far as I'm aware and I have never built an image myself, so I'd need help with that.

The compiler version should stay the same since I'm checking out a specific commit right after cloning.

From the Oding github page: "Odin only supports x86-64/amd64 at the moment (64-bit)"

**Comment by rbergen** [comment]
> There is no base image with Odin included as far as I'm aware and I have never built an image myself, so I'd need help with that.

That we can indeed help with. We have a number of docker base images within [this organization](https://github.com/PlummersSoftwareLLC) already.

> The compiler version should stay the same since I'm checking out a specific commit right after cloning.

Yes, you do. My apologies for missing this.

> From the Oding github page: "Odin only supports x86-64/amd64 at the moment (64-bit)"

Thanks for the clarification.

**Comment by omgitsmoe** [comment]
> I think we'll need to use a docker base image that has Odin baked in.

What does base image mean in this case? An image that starts `FROM scratch` or can I use the ubuntu base that I was using before and start from there, install dependencies and build the Odin compiler and then use that as base image?

**Comment by rbergen** [comment]
> What does base image mean in this case?

It's basically an image that includes the following part of your Dockerfile, pushed to Docker Hub:
```dockerfile
FROM ubuntu:20.04

# Odin needs llvm and clang for building itself as well as building .odin files on *Nix systems
RUN apt-get update -qq \
    && apt-get install -y llvm-11 clang git build-essential

WORKDIR /opt/Odin
# checkout specific commit so we have a tested version, since we're on the master branch
RUN git clone https://github.com/odin-lang/Odin.git /opt/Odin \
    && git checkout 481fc8a5b60cf15d \
    && make
```

You can then convert your Dockerfile to:
```dockerfile
FROM primeimages/odin:commit-481fc8a5b60cf15d AS build

COPY *.odin /opt/app/
WORKDIR /opt/app
RUN /opt/Odin/odin build main.odin -opt:3 -no-bounds-check -out:primes-odin-1

FROM ubuntu:20.04 AS runtime
COPY --from=build /opt/app/primes-odin-1 primes-odin-1

ENTRYPOINT [ "./primes-odin-1" ]
```

In fact, the push of the image just completed, so it should work from now on.

**Comment by omgitsmoe** [comment]
Was almost done with my version, if you want to use any of that:
```dockerfile
FROM ubuntu:20.04

# Odin needs llvm and clang for building itself as well as building .odin files on *Nix systems
RUN apt-get update -qq \
    && apt-get install -y llvm-11 clang git build-essential

WORKDIR /Odin-install
# checkout specific commit so we have a tested version, since we're on the master branch
RUN git clone https://github.com/odin-lang/Odin.git /Odin-install \
    && git checkout 481fc8a5b60cf15d \
    && make

RUN mkdir /opt/Odin
RUN cp -R ./core ./shared ./tools ./odin /opt/Odin/
WORKDIR /
RUN rm -rf /Odin-install

ENV PATH="/opt/Odin:${PATH}"
```

Thank you very much for your help!

**Comment by rbergen** [comment]
It's pushing that version to Docker Hub now.

**Comment by rbergen** [comment]
Push is done, and you're very welcome. :)

**Comment by omgitsmoe** [comment]
I updated the Dockerfile.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Comment by omgitsmoe** [comment]
@marghidanu what is not compatible with BSD-3? Do you need me to change something?

**Comment by marghidanu** [comment]
Is there a license check somewhere? I don’t see any warning about the license

**Comment by omgitsmoe** [comment]
You unchecked "All code herein is licensed compatible with BSD-3." in my opening post.

**Comment by rbergen** [comment]
I'm guessing there was an accidental click on the checkbox; it's one of the very few things one can "edit" on github without having to confirm.

**Comment by marghidanu** [comment]
Ohhh, that must’ve happened while checking the comments from my phone. Sorry about that.

**Comment by rbergen** [comment]
Guess I can still hit the green button on this PR then. :)

**Comment by marghidanu** [comment]
Definitely

**Comment by omgitsmoe** [comment]
No problem, I was just worried that I messed sth. up.

Thank you!

**Pull request merged**
