### PR TITLE
add solution in umple language

### PR DESCRIPTION
**Pull request by mmcdon20**
## Description

[Umple](https://cruise.umple.org/umple/) is a programming language / UML modelling language created by The University of Ottawa. 

This is a faithful 1-bit implementation.

Umple apparently can compile to source code in a variety of languages. This implementation targets java.  Since I am targeting java, I was able to import the `BitSet` from the java standard library, which is how I am storing the prime flags. 

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by mmcdon20** [comment]
Consider this stable. I don't intend to add/change anything else unless something comes up in review.

**Comment by rbergen** [comment]
Wow, this language gives me flashbacks to when I was using Rational Rose (before IBM bought it) to draw UML that the tool would translate to Java source files, heavily annotated with comments that tried to keep UML model and Java source connected. That sort of worked, but not really. This is an interesting more direct approach.

EDIT: after a first look at the code you submitted, I guess a one-class association- and state machine-less application does not illustrate too much of the specific capabilities of Umple over Java. :)

**Comment by mmcdon20** [comment]
> Wow, this language gives me flashbacks to when I was using Rational Rose (before IBM bought it) to draw UML that the tool would translate to Java source files, heavily annotated with comments that tried to keep UML model and Java source connected. That sort of worked, but not really. This is an interesting more direct approach.

I thought this was a pretty interesting approach too. 

> EDIT: after a first look at the code you submitted, I guess a one-class association- and state machine-less application does not illustrate too much of the specific capabilities of Umple over Java. :)

You would be right about that. This is similar to a java implementation, with a few differences. You have "depend" statements inside the classes instead of "import" statements at the top of the files. The compiler automatically generates a constructor, so there is no constructor that I have defined explicitly. I used an [after statement](https://cruise.umple.org/umple/BeforeandAfterStatements.html) to set all of the bits in the `BitSet` to 1 in the constructor of the generated code. I only just thought of this now, 
 but I could also add before statements on `getBit` and `clearBit` for assertions. I'll go ahead and add that in just to show a little bit more umple capabilities.

**Comment by mmcdon20** [comment]
I just noticed a mistake in the README file, which I corrected. 
This PR is now stable.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
