### PR TITLE
Bitmasks

### PR DESCRIPTION
**Pull request by rogiervandam**
## Description
Made significant speed improvements by grouping writes to memory:
- PrimeJavascript.js now waits for all the writes to one memory word, before committing
- PrimeJavascript_memcopy now copies words over smaller ranges
- PrimeJavascript_cluster now facilitates both algorithms across multiple workers

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by DiefBell** [comment]
I don't think `.DS_Store` files should be committed.

**Comment by rogiervandam** [comment]
> I don't think `.DS_Store` files should be committed.

Corrected. Thanks.

**Comment by DiefBell** [comment]
There's still a `.DS_Store` file in the root. @rbergen should we get this added to a `.gitignore`?

**Comment by rbergen** [comment]
@DiefBell with @rogiervandam having closed the PR I am not sure how relevant my answer to your question still is, but I'll give it anyway. The .DS_Store in the root is not part of the repository now, but would (have) be(en) introduced with the PR. It should simply not be included in it.

**Comment by rogiervandam** [comment]
Accidentally closed request.  Reopend.

**Comment by rbergen** [comment]
@rogiervandam It seems that the introduction of the `require('perf_hooks')` in PrimeJavaScript.js and PrimeJavaScript_memcopy.js breaks the Deno runs. This is the output I get when I execute a `docker run` locally:

```text
rogiervandam-node;5705;5.0000431320000205;1;algorithm=base,faithful=yes,bits=1

rogiervandam-bun;8928;5.000083417;1;algorithm=base,faithful=yes,bits=1
error: Uncaught ReferenceError: require is not defined
const { performance } = require('perf_hooks');
                        ^
    at file:///opt/app/PrimeJavaScript.js:20:25

rogiervandam-memcopy-node;11735;5.000339586999965;1;algorithm=other,faithful=yes,bits=1
error: Uncaught ReferenceError: require is not defined
const { performance } = require('perf_hooks');
                        ^
    at file:///opt/app/PrimeJavaScript_memcopy.js:20:25

rogiervandam-memcopy-bun;17618;5.000472283;1;algorithm=other,faithful=yes,bits=1

rogiervandam-cluster-base-node;14617;5.053010843999917;4;algorithm=base,faithful=yes,bits=1

rogiervandam-cluster-memcopy-node;30172;5.058445269000018;4;algorithm=other,faithful=yes,bits=1

diefbell-worker-node;13135;5.071487028000061;4;algorithm=base,faithful=yes,bits=1
```

I assume this is not intentional?

**Comment by rogiervandam** [comment]
> @rogiervandam It seems that the introduction of the `require('perf_hooks')` in PrimeJavaScript.js and PrimeJavaScript_memcopy.js breaks the Deno runs. This is the output I get when I execute a `docker run` locally:
> 
> ```
> rogiervandam-node;5705;5.0000431320000205;1;algorithm=base,faithful=yes,bits=1
> 
> rogiervandam-bun;8928;5.000083417;1;algorithm=base,faithful=yes,bits=1
> error: Uncaught ReferenceError: require is not defined
> const { performance } = require('perf_hooks');
>                         ^
>     at file:///opt/app/PrimeJavaScript.js:20:25
> 
> rogiervandam-memcopy-node;11735;5.000339586999965;1;algorithm=other,faithful=yes,bits=1
> error: Uncaught ReferenceError: require is not defined
> const { performance } = require('perf_hooks');
>                         ^
>     at file:///opt/app/PrimeJavaScript_memcopy.js:20:25
> 
> rogiervandam-memcopy-bun;17618;5.000472283;1;algorithm=other,faithful=yes,bits=1
> 
> rogiervandam-cluster-base-node;14617;5.053010843999917;4;algorithm=base,faithful=yes,bits=1
> 
> rogiervandam-cluster-memcopy-node;30172;5.058445269000018;4;algorithm=other,faithful=yes,bits=1
> 
> diefbell-worker-node;13135;5.071487028000061;4;algorithm=base,faithful=yes,bits=1
> ```
> 
> I assume this is not intentional?

Missed this. Thanks. Resolved.

**Comment by rbergen** [comment]
LGTM

**Pull request merged**
