### PR TITLE
Add new Ada solution which includes optimised versions and a custom b…

### PR DESCRIPTION
**Pull request by Lucretia**
## Description
A new optimised Ada 2012 solution including a custom bit set which seems to be the fastest of them all. On single task

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@Lucretia I removed the commit list from your description. It doesn't contain any useful information and makes my scroll finger hurt. In line with that, please don't include it in any future PRs you open.

**Comment by rbergen** [comment]
@Lucretia I get the following error when attempting a docker build:
```
 => ERROR [8/9] COPY ./optimised.adc ./prime_sieve.gpr ./                                                          0.0s
------
 > [8/9] COPY ./optimised.adc ./prime_sieve.gpr ./:
------
failed to compute cache key: "/optimised.adc" not found: not found
```

Please make sure your Dockerfile works before (re)submitting your PR for review.

**Comment by Lucretia** [comment]
That was one file which I missed but was working here, obviously.

Now, having synchronised with the master branch I cannot get the thing to build using the new command  of ```make DIRECTORY=PrimeAda/solution_2``` which now outputs:

```
info: Unconfined mode: false
info: Detected architecture: amd64
info: [PrimeAda][solution_2] Building...
error: [PrimeAda][solution_2] Failed building solution!
error: No data was collected!
```

No errors other than that.

In a clean chekout in /tmp from my own branch, I can build it locally fine, so all files are now present.

**Comment by Lucretia** [comment]
Try that.

**Comment by rbergen** [comment]
Docker lint fails, see the messages under "Files changed". It's up to you in principle, but you may want to consider using a different distro (e.g. Ubuntu) as a basis.

**Comment by mike-barber** [comment]
@Lucretia I also tried building it on my machine, and ran into a bunch of errors from yum. Not sure what's up with it.

Changing to Ubuntu, which I'm familiar with, worked first time:

```Dockerfile
FROM ubuntu AS build
RUN apt-get update && apt-get install -y gnat gprbuild && rm -rf /var/lib/apt/lists/*
```
You could also use `debian:stable-slim` if you like. 

It's beneficial putting the update, install and cleanup stuff in a single RUN command as it cleans up the intermediate image before returning and results in fewer layers. Hope this helps.

**Comment by Macleykun** [comment]
> @Lucretia I also tried building it on my machine, and ran into a bunch of errors from yum. Not sure what's up with it.
> 
> Changing to Ubuntu, which I'm familiar with, worked first time:
> 
> ```dockerfile
> FROM ubuntu AS build
> RUN apt-get update && apt-get install -y gnat gprbuild && rm -rf /var/lib/apt/lists/*
> ```
> 
> You could also use `debian:stable-slim` if you like.
> 
> It's beneficial putting the update, install and cleanup stuff in a single RUN command as it cleans up the intermediate image before returning and results in fewer layers. Hope this helps.


If the contributer wishes to keep fedora. I already made a pull on their fork: https://github.com/Lucretia/Primes/pull/1
up to them :P

**Comment by rbergen** [comment]
@Lucretia Are you still working on this PR?

**Comment by rbergen** [comment]
Closing this for lack of response from contributor. It can be reopened if and when the indicated issue has been addressed.

**Pull request closed without merging**
