### PR TITLE
Rust: added non-HT run

### PR DESCRIPTION
**Pull request by mike-barber**
## Description

This is a small addition: A multithreaded run using physical cores in addition to the existing run with available hyperthreads. This is relevant for an apples-to-apples comparison of per-thread throughput.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by Freaky** [comment]
It would probably be wise to deduplicate the vec so platforms without HT don't end up running the same test again.

**Comment by mike-barber** [comment]
> It would probably be wise to deduplicate the vec so platforms without HT don't end up running the same test again.

Thanks @Freaky - I forgot about that.

**Review by rbergen — APPROVED** [review]
it's nice to see another PR from one of the earliest contributors to the project! LGTM!

**Comment by mike-barber** [comment]
Thanks @rbergen! It's been ages indeed. Good to hear from you too!

**Pull request merged**
