### PR TITLE
Added implementation in Oracle PLSQL

### PR DESCRIPTION
**Pull request by fvbakel**
## Description
Added implementation in Oracle PLSQL. See README.md for the details.

## Contributing requirements
* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
Please fix the CI errors for your solution in order to move forward.

**Comment by fvbakel** [comment]
@marghidanu I fixed the original issue with a workaround. However the build still fails due to lack of diskspace. I don't know how to solve that.

**Comment by rbergen** [comment]
The technical issue here is that the base image is so big (6.5+GB) that it breaks our CI. I also think that's too much to be able to include it in our automated benchmark run. 

However, there is a more fundamental problem of a different nature. That is that the Dockerfile pulls in Oracle XE, which is commercial software with a proprietary license. I don't think we can pull that into the project without exposing ourselves and those cloning or forking the repo to legal risk I simply can't accept. 

Regretfully, this means that I will have to conclude that we will not be able to merge this.

**Comment by fvbakel** [comment]
@rbergen I don't want to get involved in license issues, so thank you for the warning. I thought it should be fine because the Docker image is build with tools provided by Oracle and the [Oracle-XE](https://www.oracle.com/database/technologies/appdev/xe.html) site reads:

>You get an Oracle Database to use in any environment, plus the ability to embed and redistribute – all completely free!

But just to be on the save side, I will close this PR and remove the pre-backed Dockerfile.

**Pull request closed without merging**
