### PR TITLE
Go: improve output message

### PR DESCRIPTION
**Pull request by lrweck**
## Description
Just improved the output message to display human readable values

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [ ] I added a README.md with the right badge(s).
* [ ] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
I'm not sure I understand how this constitutes an improvement?

**Comment by lrweck** [comment]
Well, it's not an algorithmic or performance oriented one. But it improves readability.

This is the current output:
image

and this is with this commit:
image

Now "Time" is easier to understand and "Avg" shows numbers below 1ms

**Comment by rbergen** [comment]
If you can arrange for the author of the original solution to back this, I'm happy to merge it.

**Comment by rbergen** [comment]
Based on [new input from Dave](https://github.com/PlummersSoftwareLLC/Primes/pull/341#issuecomment-875952572), I'm closing this.

**Pull request closed without merging**
