### PR TITLE
PrimeSwift/solution_1 - replace ops with overflow ops & added 32bit

### PR DESCRIPTION
**Pull request by yellowcub**
## Description

**Operation Overflow:**
This update replaces several of the integer operations with overflow equivalents.  Swift by default performs overflow checking on operations such as `+`, `*`, `<<`, etc.  Switching to `&+`, `&*`, `&<<`, etc. permits the compiled routine to execute these operations in a manner consistent with C.

**Added UInt32 to Solution Mix:**
In previous commits, only `UInt` (`UInt64`)  as the Boolean array base type was included since the other `Uint` types resulted in fewer passes.  With the inclusion of the overflow operators, `UInt32` is notably faster than the original `UInt`; however, `UInt16` and `UInt8` were still slower.  Added `UInt32` as a separate dedicated run appears to be consistent with solutions in other languages.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Review by rbergen — COMMENTED** [review]
Please remove .DS_Store from your commit. We don't merge binary files.

**Comment by yellowcub** [comment]
@rbergen I think I fixed it.  Learning to use CLI.  I thought I already had `.DS_Store` in `.gitignore` when I used `git add .`.  It seems when I happen to traverse into these folders on the file browser it generates these files.  There was one in the main `Primes/` folder that was created, but I don't know that the `.gitignore` file under `PrimeSwift` can be modified to also ignore files at a higher folder level.

**Comment by rbergen** [comment]
> but I don't know that the `.gitignore` file under `PrimeSwift` can be modified to also ignore files at a higher folder level.

No, it can't.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
