### PR TITLE
3 new optimized solutions using Delphi

### PR DESCRIPTION
**Pull request by KimMadsen**
## Contributing requirements

* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [ ] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@KimMadsen Please consolidate this PR with #264, preferably combining the various implementations in one solution. I'm happy to move forward with #264 afterwards, considering the fact there has been no response from @jimmckeeth concerning #199.

**Comment by KimMadsen** [comment]
@rbergen I am not much of a Git wizard, so I am not really confident in using this web interface. I believe the two separate projects in this #281 completely replace the original Delphi project. Solution_3 is the direct replacement for the original Delphi project, (and does take the others comments into account as far as I can tell), but it does not live up to the 1 bit per potential prime storage requirement, Solution_2 does live up to that requirement.

**Comment by rbergen** [comment]
@KimMadsen In that case, I would close #264, and structure the files in this PR (#281) as follows:

- Remove the old solution_1 and make your current solution_3 in this PR replace it (as in, rename the solution_3 directory to solution_1)
- Add what is now solution_2 in this PR a second implementation in the "new" solution_1 you just created. 

None of this requires Git wizardry. You can make these changes in your local clone and push them to your fork. This PR will then update accordingly.

**Comment by KimMadsen** [comment]
As requested by @rbergen all 3 solution suggestions has been merged into the solution_1 directory.
Not that I particularly understand that requirement, since for example the C sample has two solution directories.

**Comment by rbergen** [comment]
@KimMadsen Thank you for updating your PR.

It turns out that due to changes that were made to Delphi/solution_1 since you opened this PR, we now have a merge conflict on our hands. Taking on board what you said about your familiarity with git, I would like to offer that I open a PR to replace this one, to correct this. It will apply your changes to the current state of this repo.

Of course, I will allow time for you to review said PR, so you can check if it achieves what you are aiming for.

Please let me know if this would work for you.

> Not that I particularly understand that requirement, since for example the C sample has two solution directories.

By now, there are actually four. However, they were:

- written by different authors, and/or
- require a different runtime context (Dockerfile)

I admit that the latter point is not really relevant at the moment, and I doubt it ever will be. However, we still prefer to keep the number of solutions as manageable as we can. And, if a Delphi base image does become available at some point, we're already setup to quickly adopt it.

**Comment by rbergen** [comment]
@KimMadsen Can you please indicate if I can move forward with the suggestion I made in my previous comment?

> It turns out that due to changes that were made to Delphi/solution_1 since you opened this PR, we now have a merge conflict on our hands. **Taking on board what you said about your familiarity with git, I would like to offer that I open a PR to replace this one, to correct this. It will apply your changes to the current state of this repo.**

**Comment by KimMadsen** [comment]
> @KimMadsen Can you please indicate if I can move forward with the suggestion I made in my previous comment?
> 
> > It turns out that due to changes that were made to Delphi/solution_1 since you opened this PR, we now have a merge conflict on our hands. **Taking on board what you said about your familiarity with git, I would like to offer that I open a PR to replace this one, to correct this. It will apply your changes to the current state of this repo.**

I actually responded to this a couple of times, but it seems the email reply never made it on this chat.
Feel free to use the solutions I provided, as they should cover all the bases.

**Pull request closed without merging**
