### PR TITLE
Add Visual Basic "wheel" implementations

### PR DESCRIPTION
**Pull request by Nukepayload2**
## Description

Add Visual Basic "wheel" implementations. `PrimeBASIC\solution_3` is unfaithful. `PrimeBASIC\solution_4` is faithful.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Please combine both implementations in one solution. It saves docker build time and resources during the benchmark runs.

**Comment by rbergen** [comment]
Maybe I'm jumping the gun by looking at this now, but the output I get when performing a docker run after the docker build of this image, is the following:
```
 Arguments: faithful
-f|--faithful: String
Whether to use the faithful implementation. Valid values: yes or no.
```

One interpretation of this is that your docker image expects arguments to tell it what implementation to run. That's not a setup we can support. Your docker image will have to run all (in this case both) implementations it contains, in sequence.

**Comment by rbergen** [comment]
I'm still getting the same message.

**Comment by rbergen** [comment]
I assume you're marking one implementation as unfaithful due to the use of `ArrayPool`? As `ArrayPool` is a platform-provided array allocation facility that you use to allocate and de-allocate the needed memory with every iteration, I'm actually happy to accept its use as a faithful approach.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
