### PR TITLE
Replace old code with intended solution.

### PR DESCRIPTION
**Pull request by nmerriam**
## Description
When I checked the benchmarks, the version being used in the base repository is some gash version I created to get started. It's not what I wanted to contribute. I don't understand how some old version got out and I am trying again.

## Contributing requirements
This is just an update.

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Your PR contains no changes. 

EDIT: the last push to sieve.c in your fork was made 7 days ago. Maybe what's missing is a push of your local commits to your fork?

**Comment by rbergen** [comment]
I'm closing this for now because the PR is empty. You can reopen once the changes you want to make show up in the diff between this branch and your fork.

**Comment by nmerriam** [comment]
Why does it say I have 8 commits outstanding?

Thank you in advance,

Nick

**Comment by rbergen** [comment]
Because this PR uses the same base commit as #546. If you compare the commits of that PR to the ones in this PR, you'll see that the 6 in #546 are also the first 6 of this PR. The other two commits in this PR are syncs of this repo to your fork, which don't change your solution (and shouldn't). 

The end result of that combination of commits is that your solution is exactly where it was when #546 was merged.

You can manually compare your solution's files in your fork (as in. on GitHub) to the current state of this repo. You'll find they are identical. That is to say, on GitHub your fork also contains the "old code".

**Pull request closed without merging**
