### PR TITLE
Use array slicing to provide ~30-35x improvement with pure python

### PR DESCRIPTION
**Pull request by koog1000**
### Description
Use python array slicing to improve performance. No additional libraries, follows same structure as solution 1. Syntactically it is more difficult to read, but functionally does exactly the same thing.

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* ~[ ] I added a README.md with the right badge(s).~ Not applicable
* ~[ ] I added a Dockerfile that builds and runs my solution.~ Not applicable
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@davepl I can confirm an increase from 22 iterations per 5 seconds to 483 iterations per 5 seconds on my machine, so approximately 22-fold. Do you have any objections to merging this change to your Python solution?

**Comment by davepl** [comment]
I’ll defer to the Master of Primes on this one, Rutger!

**Comment by rbergen** [comment]
I'll take that as a "no objections" 😄

**Review by rbergen — APPROVED** [review]
LGTM!

**Pull request merged**
