### PR TITLE
Julia: Move solution_2 script code into function

### PR DESCRIPTION
**Pull request by louie-github**
## Description
This PR moves the code inside the `if abspath(PROGRAM_FILE) == @__FILE__` block into a separate function.
This follows the Julia "spirit" of sorts wherein you organize code into separate functions.

This cleans up some of the `local` variable declarations in the script code and also seems to give some small improvements:

Original:
```
> julia .\Primes_original.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6739, Time: 5.0, Avg: 0.0007419498441905327, Limit: 1000000, Count: 78498
epithet-jl;6739;5.0;1;algorithm=base,faithful=yes,bits=1

> julia .\Primes_original.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6785, Time: 5.0, Avg: 0.0007369196757553427, Limit: 1000000, Count: 78498
epithet-jl;6785;5.0;1;algorithm=base,faithful=yes,bits=1

> julia .\Primes_original.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6730, Time: 5.0, Avg: 0.0007429420505200594, Limit: 1000000, Count: 78498
```
Edited:
```
> julia .\Primes.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6775, Time: 5.0, Avg: 0.0007380073800738007, Limit: 1000000, Count: 78498
epithet-jl;6775;5.0;1;algorithm=base,faithful=yes,bits=1

> julia .\Primes.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6850, Time: 5.0, Avg: 0.00072992700729927, Limit: 1000000, Count: 78498
epithet-jl;6850;5.0;1;algorithm=base,faithful=yes,bits=1

> julia .\Primes.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6886, Time: 5.0, Avg: 0.0007261109497531223, Limit: 1000000, Count: 78498
epithet-jl;6886;5.0;1;algorithm=base,faithful=yes,bits=1
```

This might be because the original `local` declarations aren't actually doing anything when run in the global scope, and so the variables are still global and suffer from the performance issues detailed in Julia's [Performance Tips](https://docs.julialang.org/en/v1/manual/performance-tips/) page. Placing them into a function should alleviate that.

## Contributing requirements

* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Tagging @epithet and allowing time for them to review and respond to this PR on their original solution, if they choose to do so.

**Comment by rbergen** [comment]
@louie-github Can you quantify the performance improvements you mention?

**Comment by louie-github** [comment]
> 
> 
> @louie-github Can you quantify the performance improvements you mention?

The performance improvements seem to be small but enough to be seen, so it's a little difficult to really quantify it.
I tried running the two files back and forth to limit the differences between each run:
```
PS D:\Office Files\Programming\Primes\PrimeJulia\solution_2> julia .\Primes.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6678, Time: 5.0, Avg: 0.0007487271638215035, Limit: 1000000, Count: 78498
epithet-jl;6678;5.0;1;algorithm=base,faithful=yes,bits=1

PS D:\Office Files\Programming\Primes\PrimeJulia\solution_2> julia .\Primes.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6659, Time: 5.0, Avg: 0.0007508634930169695, Limit: 1000000, Count: 78498
epithet-jl;6659;5.0;1;algorithm=base,faithful=yes,bits=1

PS D:\Office Files\Programming\Primes\PrimeJulia\solution_2> julia .\primes_new.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6803, Time: 5.0, Avg: 0.0007349698662354843, Limit: 1000000, Count: 78498
epithet-jl;6803;5.0;1;algorithm=base,faithful=yes,bits=1

PS D:\Office Files\Programming\Primes\PrimeJulia\solution_2> julia .\primes_new.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6796, Time: 5.0, Avg: 0.0007357268981753973, Limit: 1000000, Count: 78498
epithet-jl;6796;5.0;1;algorithm=base,faithful=yes,bits=1

PS D:\Office Files\Programming\Primes\PrimeJulia\solution_2> julia .\Primes.jl
2, 3, 5, 7, 11, …, 999953, 999959, 999961, 999979, 999983
Passes: 6679, Time: 5.0, Avg: 0.0007486150621350501, Limit: 1000000, Count: 78498
epithet-jl;6679;5.0;1;algorithm=base,faithful=yes,bits=1
```

I ran a few more runs before that, once again alternating, and saw the same pattern.
The original `Primes.jl` runs at about 6600-6700 passes, while the edited one runs at around 6750-6800 passes.
That would be about a 3% increase in speed.

It's a small difference, admittedly, so if it's not convincing enough, I am willing to close this PR.
However, I do still believe that it could be worth it to merge this, since it's a small fix, in line with what the Julia documentation itself says to help improve performance, and also since the race at the higher levels could be quite tight.

My thinking is to remove a "possible" performance downgrade. It's a sort of "anti-pattern" that actually hurts performance, rather than squeezing more out of the language.

Of course, this is at your discretion.

**Comment by rbergen** [comment]
> It's a small difference, admittedly, so if it's not convincing enough, I am willing to close this PR.

No, if there is a performance improvement that can "reasonably" be attributed to the change you're proposing, that is a reason to merge.

**Comment by louie-github** [comment]
Thank you so much for your time and consideration!

**Pull request merged**
