### PR TITLE
Pascal bitpacked implementation

### PR DESCRIPTION
**Pull request by circular17**
## Description

Bitpacked implementation for Pascal base algorithm

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Exactly how does this differ from PrimePascal/solution_1?

**Comment by circular17** [comment]
The difference is the type of NotPrimeArray here being PPackedBoolArray:

- the array is bitpacked (using bitpacked keyword) so it takes less memory
- it is a pointer to such array (allocated with GetMem)

Dynamic arrays ("array of" without size) cannot be bit-packed, at least with the version of FreePascal I am using. So I defined the type PackedBoolArray that is a static array of maximum size and allocate required memory manually with GetMem.

**Comment by benibela** [comment]
Two trivial improvements might make both solutions much faster:

* Compile it with `fpc -O4 prime` in the Dockerfile

* Only use local variables, i.e. do not use NotPrimeArray and SieveSize in the loop.

**Comment by rbergen** [comment]
@circular17 Thanks for clarifying that. :)

**Review by rbergen — COMMENTED** [review]
LGTM, but I forgot the select "Approve" when submitting my review.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
