### PR TITLE
Cl solution2 patch 2

### PR DESCRIPTION
**Pull request by mayerrobert**
## Description

Lots of changes to Common Lisp solution 2, also 2 of the solutions now are marked as faithful, as they are using bits and a class for the sieve state, waiting for feedback on that ;-)

Other changes:

- switched to an alpine docker image that already comes with a current sbcl Lisp compiler (2.1.6 is faster than the previously used 2.0.11)
- some fixes re: potential array access past the end
- validate results and print up to 100 (configurable)
- add a base algorithm with manual bit fiddling (bits are stored in a word array)
- no more hardcoded word sizes, now 32 vs 64 bits will be selected based on the predefined variable *features*
- some speedups

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Could you please squash your commits and reopen the PR? With 65 commits there's quite a lot to scroll through before you get to the PR's comment thread.

**Review by rbergen — COMMENTED** [review]
One general comment: please remove commented-out old/debug code from Dockerfile and .lisp files.

**Comment by mayerrobert** [comment]
Re: commented out code; the code was hard to write, it should be hard to read as well!!!

Just kidding, I have removed commented out code, and only left a few actual comments, I guess that's ok.

And sorry for the messy PR, sometime along the way I messed up with merging and rebasing so that my branch contained my changes 2 or three times in addition to changes from other people. I think this should be fixed now.

I think I have implemented all of your suggestions and I'm awaiting any further feedback.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
