### PR TITLE
Create prime sieve implementation in Bash

### PR DESCRIPTION
**Pull request by Nitepone**
This is a pure bash implementation with exception of usage of "awk" and "time" external commands. It uses bash builtin arithmetic blocks for all critical calculations.

The result output on my machine with a 3950x:
`Passes: 1, Time: 10408, Avg(ms): 10408, Limit 1000000, Count: 78498, Valid: 1`

Yes, it can't complete a single iteration with a 1 million limit in the 10 second runtime.

### CODE REVIEW

**Comment by ciplogic** [comment]
Still faster than C64... Awesome work!

**Comment by micwoj92** [comment]
@Nitepone Have you thought of using mawk instead of awk? It could be faster, but actually I am not sure what awk implementation do the runners (running ubuntu) use by default, it might be using mawk already.

**Comment by Nitepone** [comment]
I have updated the output to meet the original standard:
`Passes: 2, Time: 20.340799132, Avg: 10.170399566, Limit: 1000000, Count: 78498, Valid: True`

Additionally, my implementation is slightly faster now due to changes in how the bit array is allocated.


@micwoj92 I decided to remove the awk usage entirely. I can get by using bash builtin math to find the integer square roots. 

@rhbvkleef I have tried to make changes so that this is faithful to the original style. What in particular caused this PR to be marked as "unfaithful"?

**Comment by minecraftchest1** [comment]
I wish I looked here before doing the same thing.

**Comment by rbergen** [comment]
@Nitepone We are happy to work towards including your solution in the drag-race; we don't yet have a Bash implementation in the repo. I for one would **love** to have one :) 

However, to be able to do so, it would need to comply with the [contributing guidelines](https://github.com/PlummersSoftwareLLC/Primes/blob/drag-race/CONTRIBUTING.md). That also means that the PR needs to be opened on the drag-race branch of this repo, not original (formerly main).

With regards to faithful and unfaithful, a faithful implementation basically has to wrap the full sieve state in an object/class instance (or whatever a language's equivalent of that is), that is created from scratch for each run. We recognize that not all languages have such a construct. The "unfaithful" moniker should not be interpreted as criticism to the author of a solution, but as a characteristic of the implementation. The contributing guidelines I pointed to earlier elaborate on this and other characteristics we now consider relevant.
Concerning that relevance: I don't think it matters much in this case, due to the overall performance of the implementation. This stuff generally starts to matter towards the top of the performance leaderboard. :)

**Comment by rbergen** [comment]
Closing after merge of #251

**Pull request closed without merging**
