### PR TITLE
optimize V solution_1

### PR DESCRIPTION
**Pull request by Ekopalypse**
@marghidanu 
Do not add a second solution, but improve the existing solution_1

### CODE REVIEW

**Comment by marghidanu** [comment]
Looks good to me!

**Comment by marghidanu** [comment]
@Ekopalypse how much does this improve the performance?

**Comment by Ekopalypse** [comment]
@marghidanu Roughly around 40%, calculated by taking the average of 100 local runs, no docker.

**Comment by marghidanu** [comment]
@rbergen LGTM

**Pull request merged**
