### PR TITLE
Remove hash lookups from perl solution

### PR DESCRIPTION
**Pull request by bbrtj**
## Description
From 26 to 33 passes on my machine (~25% speedup)

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [ ] I placed my solution in the correct solution folder.
* [ ] I added a README.md with the right badge(s).
* [ ] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
We already have #352 open aiming to improve the Perl solution. Please discuss in that PR how to add your suggestions to it.

**Comment by bbrtj** [comment]
@rbergen that other PR creates a new solution (`solution_2`) which, while being the same algorithm, uses completely different storage. My PR does not aim to create a new solution, but speed up the current one just a bit. Also, the other PR does not need this kind of improvements, as there are no hash lookups and close to no dereferencing - I've already taken a look at it

**Comment by rbergen** [comment]
@brtastic That's obviously a fair point. @marghidanu, as this is a PR aiming to change your original implementation, I'm interested in your opinion about it.

**Comment by marghidanu** [comment]
Let’s keep the solution as is and merge #352 as a second optimized solution.

**Comment by marghidanu** [comment]
@rbergen my opinion seems to be unpopular. We will probably have two identical solutions, but if you want to merge this then do it.

**Comment by bbrtj** [comment]
@marghidanu My pull request does not change how this script works, it only moves some dereferencing + hash lookups into lexical variables, so that those (not free) operations can only be done once, instead of in every loop iteration (which included inner loops as well). Another little bit of improvement is to preallocate the array (with changing the last element index, `$#array`), which also helps perl not to waste time doing stuff over and over again.

That other PR's solution is completely different in terms of how it works, even though the algorithm is the same. The only reason I see for not merging my PR is to leave the current solution as "slow, but readable" which pushes array performance to the limit, while the other one is "fast, but tricky", which uses strings. However, no one gives points for style here, and really I don't think I made the solution that much less readable.

By denying this pull request (without disproving that it does improve performance, as I claim) the whole point of this competition will be defeated. Why should I bother min-maxing the performance and even looking at the results if I know that valid performance improvements are not accepted?

**Comment by marghidanu** [comment]
Yes, you're right. Let's merge this.

**Pull request merged**
