### PR TITLE
Fix label output in PrimeD/solution_2 so they are unique.

### PR DESCRIPTION
**Pull request by sonicrules1234**
## Description

Previously, the program output two outputs with the same label (BradleyChatha-Single-SieveRTBX) but different numbers of bits.  This gets fixed so that all the single threaded outputs have "-Xbit" appended where X is the number of bits for the output.  Note that this means that primeview might need to be changed if it keeps historical data.
## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Thanks @sonicrules1234 for identifying the duplicate labels and proposing a fix. 

Tagging @BradleyChatha to give them the opportunity to review and comment on this proposed change to their solution.

**Comment by BradleyChatha** [comment]
Ah, good catch!

Also LGTM.

**Comment by sonicrules1234** [comment]
We might also want to add the bits part to the multi-threaded ones too.

**Comment by BradleyChatha** [comment]
Yeah, go ahead with that as well if you want. Will keep things consistant.

**Comment by sonicrules1234** [comment]
Ok, done.

**Pull request merged**
