### PR TITLE
Added Go version of Sieve of Erastothenes.

### PR DESCRIPTION
**Pull request by bundgaard**
Enjoy this garbage collected version of an awesome algorithm.

### CODE REVIEW

**Comment by davepl** [comment]
Thanks!  Please make sure the README contains the info folks need to install a compiler and run it, if it does not already.

**Comment by jonsv322** [comment]
@bundgaard, you could speed up the code by only doing a de-reference only once in the loop for the sieveSize and bitArray:

```
--- a/PrimeSieveGo/main.go
+++ b/PrimeSieveGo/main.go
@@ -20,16 +20,17 @@ var myDict = map[int]int{
 func (s *Sieve) runSieve() {
        factor := 3
        var q = int(math.Sqrt(float64(s.sieveSize)))
-
+       sieveSize := s.sieveSize
+       bitArray := s.bitArray
        for factor <= q {
-               for num := factor; num < s.sieveSize; num += 2 {
-                       if s.bitArray[num] {
+               for num := factor; num < sieveSize; num += 2 {
+                       if bitArray[num] {
                                factor = num
                                break
                        }
```

also there is a bug in the code, the initBitArray needs to be clear for each run:
```
@@ -93,10 +94,10 @@ func main() {
        startClock := time.Now()
 
        initBitArray := make([]bool, 1e6)
-       for i := range initBitArray {
-               initBitArray[i] = true
-       }
        for {
+               for i := range initBitArray {
+                       initBitArray[i] = true
+               }

```

**Comment by bundgaard** [comment]
Thanks for feedback, @jonsv322
I will update the README with link to golang.org/dl. @davepl

**Comment by jonsv322** [comment]
@bundgaard, I have one more speed up that make this GO version faster that CPP at least on my machine:

```
jwiden@debian-testing:~/src/Primes/PrimeSieveGo (main)$ go run main.go
Passes: 9278, Time: 5000483474, Avg: 0.000000, Limit: 1000000, Count1: 78498, Count2: 78498, Valid: true

jwiden@debian-testing:~/src/Primes/PrimeCPP (main)$ ./run.sh 
Passes: 8879, Time: 5.000000, Avg: 0.000563, Limit: 1000000, Count1: 78498, Count2: 78498, Valid: 1
```

```
@@ -87,16 +88,27 @@ func (s Sieve) Results(showResults bool, duration time.Duration, passes int) {
                s.countPrimes(), /* countPrimes() */
                s.Validate() /* validateResults*/)
 }
+
+func memsetRepeat(a []bool, v bool) {
+    if len(a) == 0 {
+        return
+    }
+    a[0] = v
+    for bp := 1; bp < len(a); bp *= 2 {
+        copy(a[bp:], a[:bp])
+    }
+}
+
 func main() {
 
        passes := 0
        startClock := time.Now()
 
        initBitArray := make([]bool, 1e6)
-       for i := range initBitArray {
-               initBitArray[i] = true
-       }
+
+

```

**Comment by bundgaard** [comment]
@jonsv322 that sounds amazing, where should I call the memsetRepeat?

**Comment by jonsv322** [comment]
@bundgaard, sorry missed a bit in the diff:

```
        initBitArray := make([]bool, 1e6)
-       for i := range initBitArray {
-               initBitArray[i] = true
-       }
+
+
        for {
+               memsetRepeat(initBitArray, true);
                sieve := Sieve{bitArray: initBitArray, sieveSize: 1e6}
```

**Pull request merged**
