### PR TITLE
Object Pascal implementation by rbergen

### PR DESCRIPTION
**Pull request by rbergen**
## Description

This is an implementation in Object Pascal, or Free Pascal "ObjFPC mode" to be exact.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct category folder.
* [x] I added a README.md or Dockerfile.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
Cool, this looks good to go.

**Comment by rbergen** [comment]
I have a Ruby implementation lined up as well. I assume it is best to just hold on to that until this PR is merged?

**Comment by marghidanu** [comment]
Done :)

**Comment by marghidanu** [comment]
I super curious how the ruby implementation compares to the Python and Perl one

**Comment by rbergen** [comment]
Well... Don't get your hopes up, is all I will say ;)

**Pull request merged**
