### PR TITLE
Fastware C++ solution

### PR DESCRIPTION
**Pull request by zukas**
## Description
Fastware C++ table based implementation

* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
I'm afraid we can't accept solutions that include binary files.

**Comment by zukas** [comment]
How about now?

**Comment by rbergen** [comment]
I still see a binary called fastware in the PR.

**Comment by zukas** [comment]
Fixed

**Comment by rbergen** [comment]
Ok, I've looked at it and thought about it, and my conclusion is this: this is not a solution testing the speed of a prime sieve implementation, but a solution testing how quickly C++ can count a list of hard-coded numbers. The code performing the sieve run isn't even in the executable that contains the timed loop.

@marghidanu Unless you disagree, I'm going to close this.

**Comment by marghidanu** [comment]
No objections here

**Comment by zukas** [comment]
> Ok, I've looked at it and thought about it, and my conclusion is this: this is not a solution testing the speed of a prime sieve implementation, but a solution testing how quickly C++ can count a list of hard-coded numbers. The code performing the sieve run isn't even in the executable that contains the timed loop.
> 
> @marghidanu Unless you disagree, I'm going to close this.

Thanks

**Pull request closed without merging**
