### PR TITLE
Prime JavaScript

### PR DESCRIPTION
**Pull request by DiefBell**
## Description
Converted PrimeNodeJS to PrimeJavaScript as NodeJS is the runtime, not the language, and this also allows us to run on other runtimes.

This has been created in response to the comment left on my previous PrimeBun pull request: https://github.com/PlummersSoftwareLLC/Primes/pull/848#issuecomment-1179072059

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@DiefBell Thank you for submitting this and including Deno in the updated solution. That's highly appreciated!

**Comment by rbergen** [comment]
The `docker build` fails for this solution. It looks like the `bun:edge` Docker image is based on Alpine, which means apt-get isn't available.

**Comment by DiefBell** [comment]
It was Ubuntu based yesterday.... 🤦 I'll go sort

**Comment by DiefBell** [comment]
This is definitely still Ubuntu based, and I can build it locally no problem... Really not sure what the issue is here, will keep investigating

**Comment by rbergen** [comment]
I'm basing my Alpine conclusion mainly on this layer in the `bun:edge` image:

```Dockerfile
ENV GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc
```

Taking steps to include glibc is indeed common in Alpine, as it doesn't include it by default.

**Comment by DiefBell** [comment]
Turns out Docker was caching something somewhere, after a prune I've got this error too. Will sort it out

**Comment by DiefBell** [comment]
Should be good to go

**Review by rbergen — COMMENTED** [review]
Hadolint identified a couple of issues with your Dockerfile. Could you please address those?

**Comment by DiefBell** [comment]
Fixed

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by DiefBell** [comment]
LGTM?

**Comment by rbergen** [comment]
Looks Good To Me. That's me telling the second maintainer I'm happy to merge if he also agrees.

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
