### PR TITLE
reset bitArray values between runs

### PR DESCRIPTION
**Pull request by MikeAWilliams**
## Description
Go makes a shallow copy of slices. So, the existing go solution only performs the prime sieve once and after that gets the slice with the solution already in place. I just made a quick fix to initialize the slice before every run.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
Well spotted!

**Review by marghidanu — APPROVED** [review]

**Comment by marghidanu** [comment]
LGTM

**Review by rbergen — APPROVED** [review]
LGTM too, and if I'm honest I feel remiss for not seeing this earlier.

**Comment by marghidanu** [comment]
I know, me too :) but we have a lot of languages on our hands.

**Pull request merged**
