### PR TITLE
Rust `solution_1` bit storage improvements

### PR DESCRIPTION
**Pull request by mike-barber**
## Description

This PR adds a variant of `striped-bits` that addresses the locality problem with the original one. It was always pretty fast on CPUs with plenty of cache, but performed pretty poorly on smaller CPUs. This solves the locality problem by dealing with smaller blocks that fit better in cache.

Changes: 
- corrected extra iteration bug on main sieve
- added more cache-friendly `FlagStorageBitVectorStripedBlocks` version of the striped implementation
- simplified stripe/word accounting on `FlagStorageBitVectorStriped` based on learnings from the above
- added more tests to validate storage directly

@rbergen - apologies for the recent frequency of PRs for this solution. I'm hoping this is the last one for a while - this was the last big thing to address. 

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@mike-barber I was wondering if these latest implementations rely on some form of one-time calculation of bitmaps (blocks) that are then projected on the sieve?

**Comment by mike-barber** [comment]
@rbergen no luckily not :) It's the same algorithm as before, but I've just broken the work set up into smaller blocks that fit in the cache better. 

Before, I was running over the entire sieve 8 times -- one for each bit. Now, I run over a smaller part of the sieve (a block) 8 times (one for each bit), then proceed to the next block. 

The way the bits are masked and applied is still calculated on the fly. I think that's what you're asking, but I may have misunderstood :) 
```rust
// get mask for this bit position
let mask = !(1 << bit_idx);

// unrolled loop
while word_idx < effective_len.saturating_sub(skip * 3) {
    // Safety: we have ensured that (word_idx + skip*N) < length
    unsafe {
        *block.get_unchecked_mut(word_idx) &= mask;
        *block.get_unchecked_mut(word_idx + skip) &= mask;
        *block.get_unchecked_mut(word_idx + skip * 2) &= mask;
        *block.get_unchecked_mut(word_idx + skip * 3) &= mask;
    }
    word_idx += skip * 4;
}
...
```

**Comment by rbergen** [comment]
@mike-barber Your phrasing of the question would indeed have boiled down to the same thing; mine just felt a little easier to type in. :)

In any case, thank you for your explanation!

**Comment by mike-barber** [comment]
You're welcome! I'm glad I answered the right question - I'm really good at answering completely the wrong one at times.

**Pull request merged**
