### PR TITLE
Added Nim solution #2

### PR DESCRIPTION
**Pull request by beef331**
## Description

Copy of solution 1 with the following changes:
- Added a `bitlist` for more optimized storage/access
- Flicked the `danger` switch, enabled link time optimizations, and native march.  Since speed is the game
## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right category badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
Ok, got it why you close it!

**Comment by marghidanu** [comment]
Please keep in mind that we also run solutions on ARM64, the current Docker image you are using doesn't have support for the arm64 platform. Please consider using Alpine as a base image and install nim at build time.

**Comment by beef331** [comment]
The reason I closed the other one was that I did not realize the "class" restriction (makes no sense in this case as it's a single object without any overriding)  so guessed it wasnt right as it didnt use anything close to classes (array and static dispatch). No clue about docker, so I might eventually get that done, but no clue when

**Comment by marghidanu** [comment]
Well, I guess we can ignore the ARM64 build for your solution, but otherwise, this looks good to me.

**Pull request merged**
