### PR TITLE
COMAL solution that runs within Docker

### PR DESCRIPTION
**Pull request by rbergen**
## Description
This is an adaptation of the COMAL solution submitted by @mkott that runs in Docker.

## Contributing requirements
* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
Wow! LGTM

**Review by marghidanu — APPROVED** [review]

**Comment by rbergen** [comment]
Thanks, @marghidanu :)

**Comment by kottm** [comment]
This looks good, thanks for doing this! As you say, the timing precision is hindered by SYS(now) only being in whole seconds, but at least COMAL is now in the race, albeit way back near the end.

**Comment by rbergen** [comment]
> This looks good, thanks for doing this! 

Thank you, and you're welcome!

> As you say, the timing precision is hindered by SYS(now) only being in whole seconds, but at least COMAL is now in the race, albeit way back near the end.

To be frank, with the duration of the sieve run being what it is, I don't think the digits to the right of the decimal point matter too much for the solution's ranking. :)
 
From a conceptual standpoint, I just love the fact that we have this "1970s/1980s language" running on technology that is current in 2021, regardless of its place on the leaderboard.

**Pull request merged**
