### PR TITLE
 rust solotion2

### PR DESCRIPTION
**Pull request by abdellatif-temsamani**
## rust solution 2

removed unneeded `return` and print statements
followed `cargo clippy` as a guide for cleaning

## Contributing requirements

- [X] I read the contribution guidelines in CONTRIBUTING.md.
- [X] I placed my solution in the correct solution folder.
- [X] I added a README.md with the right badge(s).
- [ ] I added a Dockerfile that builds and runs my solution.
- [ ] I selected `drag-race` as the target branch.
- [ ] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by Macleykun** [comment]
Heya, i saw your PR and wanted to ask about this: https://github.com/PlummersSoftwareLLC/Primes/blob/f5cf09ccee99ee5a43fbe0f8eb10063d609a57be/PrimeAda/solution_1/Dockerfile#L24
It doesn't seem to add anything, perhaps it was a typo?

**Comment by rbergen** [comment]
@abdellatif-dev This PR doesn't seem to include any improvements to the performance of the benchmarked part of the solution. As per the contributing guidelines, we will not merge this unless you arrange support from the solution's original author, yourself.
I'll wait a week to see if such approval is given. If not, I'll close this.

**Comment by abdellatif-temsamani** [comment]
> Heya, i saw your PR and wanted to ask about this:
> 
> https://github.com/PlummersSoftwareLLC/Primes/blob/f5cf09ccee99ee5a43fbe0f8eb10063d609a57be/PrimeAda/solution_1/Dockerfile#L24
> 
> 
> It doesn't seem to add anything, perhaps it was a typo?

@Macleykun 
i worked on solotion number 2

**Comment by abdellatif-temsamani** [comment]
> @abdellatif-dev This PR doesn't seem to include any improvements to the performance of the benchmarked part of the solution. As per the contributing guidelines, we will not merge this unless you arrange support from the solution's original author, yourself. I'll wait a week to see if such approval is given. If not, I'll close this. 
@rbergen 
i have a question if i revert the changes and created my solution and had improvements will it be accepted?

**Comment by Macleykun** [comment]
> > Heya, i saw your PR and wanted to ask about this:
> > https://github.com/PlummersSoftwareLLC/Primes/blob/f5cf09ccee99ee5a43fbe0f8eb10063d609a57be/PrimeAda/solution_1/Dockerfile#L24
> > 
> > It doesn't seem to add anything, perhaps it was a typo?
> 
> @Macleykun i worked on solotion number 2

Yes I can see that, however you’ve added that line. But it doesn’t add anything. It’s better to remove it :-).

**Comment by abdellatif-temsamani** [comment]
> > > Heya, i saw your PR and wanted to ask about this:
> > > https://github.com/PlummersSoftwareLLC/Primes/blob/f5cf09ccee99ee5a43fbe0f8eb10063d609a57be/PrimeAda/solution_1/Dockerfile#L24
> > > 
> > > It doesn't seem to add anything, perhaps it was a typo?
> > 
> > 
> > @Macleykun i worked on solotion number 2
> 
> Yes I can see that, however you’ve added that line. But it doesn’t add anything. It’s better to remove it :-).

i'll remove it right away

**Comment by rbergen** [comment]
@abdellatif-dev No, because then we would have the conversation about the fact that there are already 7 Rust solutions in place, and an 8th one would have to be revolutionarily different than the 7 existing ones, to be accepted. 

Your path to having your changes merged really is getting approval from solution_2's original author.

**Comment by abdellatif-temsamani** [comment]
I'm sorry I couldn't get confirmation from the Owner I guess I have to close it when I soon

**Comment by abdellatif-temsamani** [comment]
I'm sorry I couldn't get confirmation from the Owner I guess I have to close it when I soon

**Comment by rbergen** [comment]
I will in fact close this, for now. If you manage to secure approval from the original author of Rust/solution_2 at a later them, then do feel free to reopen it.

**Pull request closed without merging**
