### PR TITLE
Pascal solution 3

### PR DESCRIPTION
**Pull request by olivierbrun**
## Description

Implemented an optimized implemention of the base algorithm in freepascal. The optimization in the constructor should provide some boost. This implementation is quite close to Dave's original source which should provide some fair comparison with other language.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
This solution has the same key characteristics (base algorithm, faithful, 1 bit per prime) as PrimePascal/solution_2 does. That means that in principle, we won't merge this as a new solution.
If you believe you can make changes to solution_2 that improve its performance, then please structure your PR as one that modifies said solution accordingly.

**Comment by olivierbrun** [comment]
hello Rutger, thanks for the quick feedback, I agree with your comment. 
I'll update my code to propose a different and hopefully faster algorithm, also providing ability to optionally handle multithreading.

**Comment by rbergen** [comment]
@olivierbrun Thank you, and that's perfectly fine. Is it okay with you if we close this PR while you work on that, and have you open a new one when you feel it's ready to merge?

**Comment by olivierbrun** [comment]
Let's close this PR, and I'll push a new one.

**Pull request closed without merging**
