### PR TITLE
add second zig solution

### PR DESCRIPTION
**Pull request by ManDeJan**
## Description
Hi!, I finally got around to making this pull request. This version of the zig code uses aligned memory and code execution for more consistent and slightly improved performance over the existing solution. I made it to show off the fine grained yet easy to use control you get over the code execution in Zig. Also added some additional sieves if people want to have a look at different implementations :-).

## Contributing requirements
* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right category badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Adding a link to [this comment](https://github.com/PlummersSoftwareLLC/Primes/pull/200#issuecomment-847082698) in PR #200, as it relates to this PR.

**Comment by marghidanu** [comment]
Any reason why this is not merged yet?

**Comment by ManDeJan** [comment]
Yes, see (https://github.com/PlummersSoftwareLLC/Primes/pull/200). I'll push the new version soon :)

**Comment by ManDeJan** [comment]
I pushed the new version! It contains two sieves, one working on a bitset and one working with bytes. The latter is the fastest faithfull implementation on my system so far! It gets `18250`+ iterations on my system while the bitset implementation  comparable to `std::vector<bool>` in C++ gets around `11000` iterations. All the tests were run on a Ryzen 3700x @ 4.1GHz. Big thanks to @ityonemo for helping out and collaborating :-).  Should be good to merge now!

**Comment by marghidanu** [comment]
#200 has been closed since yesterday, that's why I'm asking :)

**Comment by ityonemo** [comment]
@marghidanu just fyi we're going to probably have a multithreaded one by the weekend (day jobs, and all that).

**Comment by marghidanu** [comment]
Looks like the build failed. :(

**Comment by ManDeJan** [comment]
I see the CI failed because it uses an relatively "ancient" version of zig that doesn't support the bitset sieve yet, is there an easy way to use a newer version of the language?

**Comment by marghidanu** [comment]
CI is building your Dockerfile, I suggest switching to alpine:3.13 and install zig(0.7.1-r0) in there. Let me know if you need any help

**Comment by ManDeJan** [comment]
We need a even more recent version, zig 0.7.1 is ~6 months old, I found [this](https://hub.docker.com/r/euantorano/zig) docker image that has zig with a build of the master branch. I have no experience with docker, but would it be as simple as changing the docker file to:

```dockerfile
FROM euantorano/zig:master

WORKDIR /opt/app
COPY . .
RUN zig build -Drelease-fast

ENTRYPOINT [ "./zig-cache/bin/PrimeZig" ]
```

**Comment by marghidanu** [comment]
Do you need to use the nightly build for Zig? Otherwise, I strongly suggest you use a stable verified image, alpine is small stable, and verified. Also, it has support for ARM64.

**Comment by ManDeJan** [comment]
0.7.1 is the latest stable release, which as said unfortunatly doesn't support the bit sieve in this PR. I think the options are using a nightly build of zig or removing the bit sieve from the build for now. The image I proposed is also based upon alpine linux so it should be small and stable as well :). Let me know what you'd prefer!

**Comment by marghidanu** [comment]
Ok, let's just go with the image proposed by you then.

**Comment by rbergen** [comment]
Builds are still failing. Is this expected at this time?

**Comment by ManDeJan** [comment]
Closed in favor of #241

**Pull request closed without merging**
