### PR TITLE
D Solution 2 additions

### PR DESCRIPTION
**Pull request by BradleyChatha**
## Description
My apologies.

#541 

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
- Please limit your algorithm qualifications to "base", "wheel" and "other". 
- The set of implementations in this solution now looks like the full range of permutations of a number of implementation variations you have implemented. I'd like to ask you to please consider "cherry picking" a subset of them, being those that illustrate something that is specifically interesting, individually or as (sub)groups. Of course, "interesting" should primarily be considered from a perspective of performance.

**Comment by BradleyChatha** [comment]
Added a --mode argument.

The Dockerfile defaults to using `-m leaderboard` which runs the runtime 1-bit, runtime 8-bit, and compile time impls (even though it's unfaithful). These are ran in single threaded and static threaded modes, so 3 single threaded and 3 multithreaded impls.

Hope that's ok now :)

**Comment by rbergen** [comment]
> Hope that's ok now :)

Yes, and I can say that I think this is actually a very elegant way to implement this. Thank you for it!

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
