### PR TITLE
Java solutions using raw integer storage and bit manipulation

### PR DESCRIPTION
**Pull request by chrvanorle**
## Description

These are faithful Java implementations of the base algorithm using boolean/byte/int/long arrays. The first being an 8 bit implementations and the others being 1 bit. Multithreading is supported for all implementations. The Dockerfile will run all implementations both single threaded and multithreaded.

The I32 and I64 versions are about twice as fast as the BitSet 1-bit solution_2 (710/s vs 364/s). Even though i thought the 64 bit implementation would be faster, the 32 bit one outperforms it on every machine i tried it on.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Would it be fair to say that the "boolean" implementation is conceptually the same as Java/solution_1? Because in that case I would like to pull that particular implementation out and have the solution focus on the ones that are indeed different.

**Comment by chrvanorle** [comment]
The bool solution indeed ended up very similar to solution_1, so i removed it.

**Comment by chrvanorle** [comment]
I've added solutions that cache the masks used. I get mixed performance results, for some CPU's it seems the caching performs worse then just doing the operations, so i keep both. I'll update the readme with results when i get the time.

**Comment by rbergen** [comment]
> I've added solutions that cache the masks used. I get mixed performance results, for some CPU's it seems the caching performs worse then just doing the operations, so i keep both. I'll update the readme with results when i get the time.

That's fine, but then I'll hold on reviewing and merging this, until then.

**Comment by chrvanorle** [comment]
Added I64PatternCalc, which i believe is an 'other' algorithm due to using masks to clear multiple prime candidates per write. The results have also been added.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
