### PR TITLE
Sed fix

### PR DESCRIPTION
**Pull request by marghidanu**
Fix for issue #296 

The fix should be validated for the following operating systems:

* [x] macOS BigSur
* [x] macOS Catalina
* [x] Ubuntu 20.04
* [x] Windows (WSL)

### CODE REVIEW

**Comment by rbergen** [comment]
I can perform the validation on WSL2, hopefully later tonight.

**Comment by marghidanu** [comment]
Thank you, I was wondering if you can help with the WSL validation.

**Review by rbergen — APPROVED** [review]
Why not use my lunchbreak for this? 

* [X] Windows (WSL)

LGTM otherwise, as well.

**Comment by marghidanu** [comment]
Thank you @rbergen hopefully you still got some food.

**Comment by rbergen** [comment]
There is a benefit to the fact that there is some time to kill between typing "make" and seeing the final result. :)

**Pull request merged**
