### PR TITLE
results from IBM compiler:

### PR DESCRIPTION
**Pull request by awierzch**
## Description
This code is based on https://github.com/PlummersSoftwareLLC/Primes/tree/drag-race/PrimeCOBOL/solution_1.

I took the above code and made some minor changes to properly compile and run it on a real mainframe.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [ ] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
As much as I am genuinely charmed by this, I don't think we can merge it into the solution tree. Not mentioning some smaller technicalities, the main problem is that we have no IBM mainframe to run the benchmarks on. We're now at a point where we really can't merge anything new that we can't include in the benchmark. 

May I suggest to open a "show and tell" post in Discussions, and post this there?

**Comment by rbergen** [comment]
Tagging @fvbakel. I imagine you'll like this, too :)

**Comment by fvbakel** [comment]
@rbergen Thanks for mentioning this!

@awierzch Great that you took the effort for the IBM compile, I don't have access to such hardware. I did notice that the time is 50 in your output. Is there a dot missing?

**Comment by rbergen** [comment]
It seems GitHub lacks at least one feature, being the ability to convert a PR into a show and tell Discussions post...
Be that as it may, I will have to close this.

**Comment by awierzch** [comment]
> As much as I am genuinely charmed by this, I don't think we can merge it into the solution tree. Not mentioning some smaller technicalities, the main problem is that we have no IBM mainframe to run the benchmarks on. We're now at a point where we really can't merge anything new that we can't include in the benchmark.
> 

No problem, just wanted to share my results and compare GNU compiler on PC with IBM compiler on mainframe.

**Comment by awierzch** [comment]
> @rbergen Thanks for mentioning this!
> 
> @awierzch Great that you took the effort for the IBM compile, I don't have access to such hardware. I did notice that the time is 50 in your output. Is there a dot missing?

Yes. I was too lazy to fix this.

**Comment by andrew890** [comment]
I have been putting together some specific IBM mainframe z/OS adaptations so I have included the changes in that:
https://github.com/andrew890/Primes-zOS

**Pull request closed without merging**
