### PR TITLE
Update PrimeSieveJulia.jl

### PR DESCRIPTION
**Pull request by JoelTrent**
## Description

This is an update to an existing implementation in Julia (Julia Solution 1)

I profiled the code using Julia's @profiler and found that all of the computational cost was found in the for loop at line 37-39. 
I have created a vectorised version of that line using a range (similar to that seen in Julia Solution 2 for this project) that increases the speed of your code by ≈30 times!

Currently, on my machine, the implementation can do ≈ 200 passes. Conversely, vectorising the for loop enables it to do ≈ 6800 passes.

For convenience in demonstrating that this range is iterating through identical values as the previous for loop I have supplied a function called rangeTest, that demonstrates that the two approaches are equivalent. 

This is my first [proposed] contribution to a community Github project, which is exciting for me! I hope you like the change.

Joel

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by tjol** [comment]
Do you understand why this change makes a difference? I thought one of the main selling points of Julia's JIT was that you'd get the same performance no matter if you wrote in a vectorized or looping style.

Does this have something to do with the typing issue brought up in #397 ?

**Comment by JoelTrent** [comment]
I believe it's because the range that is being iterated over can't be easily determined at compile-time, so the JIT is incapable of creating a loop that is as efficient as a vectorised operation. That's what makes sense to me, but I will be the first to admit that I'm very much still learning Julia as a language.

I'd note that changing to the BitVector from the BitArray, as in #397, makes no difference to speed when replacing the for loop with a vectorised solution. It still hits ≈6800 passes regardless of that type. So in terms of the best solution for speed, I'd recommend this one in #401.

I think the relative performance of my machine and Ben's is potentially a bit different but:
In a bid to make the for loop a somewhat helpful/possible alternative, we can combine #397 with some performance annotations to get up to ≈2800 passes. 

This is is still smaller than 6800, but it's significantly better than the original 200 and adds onto the 1500 (2500 on my machine) passes that #397 was able to make. Once we add these, the JIT can do a slightly better job in this case (see https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-annotations), performing closer to the vectorised solution. It could be valuable to add this as a third solution to demonstrate how to speed up Julia for loops, although the speed up isn't very large when including #397 (≈2.5 times faster than original solution with below for loop, but only 1.1 times faster than the solution including 397).

To get to ≈2800 passes, including the change from #397, the for loop becomes:
`@simd for num in factor*3:factor*2:sieve.sieveSize`
`     @inbounds sieve.rawbits[Int((num+1)/2)] = false`
`end`

edit: displaying code legibly

**Comment by louie-github** [comment]
If it helps any, I tried to create an MWE to compare between a manual loop-and-setindex and a vectorised-setindex:

```julia
setrange(arr, r, i) = @inbounds arr[r] .= i

function setrange2(arr, r,  v)
    for ind in r
        @inbounds arr[ind] = v
    end
end

x = trues(100);
```

Below is the generated assembly via `@code_native`.
<details>
<summary> For loop </summary>

```asm
julia> @code_native syntax=:intel setrange2(x, 1:2:10, false)
        .text
; ┌ @ REPL[8]:2 within `setrange2'
; │┌ @ range.jl:670 within `iterate'
; ││┌ @ range.jl:517 within `isempty'
; │││┌ @ operators.jl:204 within `!='
; ││││┌ @ promotion.jl:410 within `=='
        mov     rax, qword ptr [rsi]
        mov     r8, qword ptr [rsi + 16]
; │││└└
; │││┌ @ operators.jl:305 within `>'
; ││││┌ @ int.jl:83 within `<'
        cmp     qword ptr [rsi + 8], 0
        setg    cl
; │││└└
; │││┌ @ operators.jl:204 within `!='
; ││││┌ @ promotion.jl:410 within `=='
        cmp     rax, r8
; │││└└
; │││┌ @ operators.jl:305 within `>'
; ││││┌ @ int.jl:83 within `<'
        setl    r9b
; │││└└
; │││┌ @ operators.jl:204 within `!='
; ││││┌ @ promotion.jl:410 within `=='
        cmp     rax, r8
; │└└└└
        je      L32
; │ @ REPL[8] within `setrange2'
        xor     cl, r9b
; │ @ REPL[8]:2 within `setrange2'
        jne     L131
; │ @ REPL[8]:3 within `setrange2'
; │┌ @ bitarray.jl:699 within `setindex!'
; ││┌ @ Base.jl within `getproperty'
L32:
        mov     rcx, qword ptr [rdi]
        mov     r9, qword ptr [rcx]
        test    dl, 1
; │└└
        jne     L90
        nop
; │┌ @ bitarray.jl:699 within `setindex!'
; ││┌ @ bitarray.jl:685 within `unsafe_bitsetindex!'
; │││┌ @ bitarray.jl:126 within `get_chunks_id'
; ││││┌ @ int.jl:86 within `-'
L48:
        lea     rdx, [rax - 1]
; ││││└
; ││││┌ @ bitarray.jl:119 within `_div64'
; │││││┌ @ int.jl:462 within `>>' @ int.jl:455
        sar     rdx, 6
; ││└└└└
; ││┌ @ bitarray.jl:686 within `unsafe_bitsetindex!'
; │││┌ @ bitarray.jl:690 within `_unsafe_bitsetindex!'
; ││││┌ @ int.jl:464 within `<<' @ int.jl:457
        lea     ecx, [rax - 1]
; │││└└
; │││┌ @ bitarray.jl:693 within `_unsafe_bitsetindex!'
; ││││┌ @ int.jl:285 within `~'
        mov     rdi, -2
        rol     rdi, cl
; ││││└
; ││││┌ @ array.jl:839 within `setindex!'
        and     qword ptr [r9 + 8*rdx], rdi
        mov     rcx, qword ptr [rsi + 8]
; │└└└└
; │┌ @ range.jl:674 within `iterate'
        add     rcx, rax
; ││┌ @ promotion.jl:410 within `=='
        cmp     rax, r8
        mov     rax, rcx
; │└└
        jne     L48
        jmp     L131
; │ @ REPL[8] within `setrange2'
L90:
        mov     ecx, 1
        nop
; │ @ REPL[8]:3 within `setrange2'
; │┌ @ bitarray.jl:699 within `setindex!'
; ││┌ @ bitarray.jl:685 within `unsafe_bitsetindex!'
; │││┌ @ bitarray.jl:126 within `get_chunks_id'
; ││││┌ @ int.jl:86 within `-'
L96:
        lea     rdx, [rax - 1]
; ││││└
; ││││┌ @ bitarray.jl:119 within `_div64'
; │││││┌ @ int.jl:462 within `>>' @ int.jl:455
        sar     rdx, 6
; ││└└└└
; ││┌ @ bitarray.jl:686 within `unsafe_bitsetindex!'
; │││┌ @ bitarray.jl:690 within `_unsafe_bitsetindex!'
; ││││┌ @ int.jl:464 within `<<' @ int.jl:457
        lea     edi, [rax - 1]
        shlx    rdi, rcx, rdi
; │││└└
; │││┌ @ bitarray.jl:693 within `_unsafe_bitsetindex!'
; ││││┌ @ array.jl:839 within `setindex!'
        or      qword ptr [r9 + 8*rdx], rdi
        mov     rdx, qword ptr [rsi + 8]
; │└└└└
; │┌ @ range.jl:674 within `iterate'
        add     rdx, rax
; ││┌ @ promotion.jl:410 within `=='
        cmp     rax, r8
        mov     rax, rdx
; │└└
        jne     L96
L131:
        ret
        nop     word ptr cs:[rax + rax]
; └
```
</details>

<details>
<summary>Vectorized</summary>

```asm
julia> @code_native syntax=:intel setrange(x, 1:2:10, false)
        .text
; ┌ @ REPL[5]:1 within `setrange'
        push    rbp
        mov     rbp, rsp
        push    r15
        push    r14
        push    r13
        push    r12
        push    rbx
        and     rsp, -32
        sub     rsp, 192
        mov     dword ptr [rsp + 12], r8d
        mov     r13, rdx
        mov     qword ptr [rsp + 16], rsi
        mov     qword ptr [rsp + 24], rdi
        vxorps  xmm0, xmm0, xmm0
        vmovaps ymmword ptr [rsp + 32], ymm0
        mov     rbx, qword ptr fs:[0]
; │┌ @ broadcast.jl:1212 within `dotview'
; ││┌ @ views.jl:133 within `maybeview'
; │││┌ @ subarray.jl:178 within `view'
; ││││┌ @ subarray.jl:209 within `unsafe_view'
; │││││┌ @ subarray.jl:28 within `SubArray'
; ││││││┌ @ multidimensional.jl:789 within `ensure_indexable'
        mov     qword ptr [rsp + 32], 8
        mov     rax, qword ptr [rbx - 32768]
        mov     qword ptr [rsp + 40], rax
        lea     rax, [rsp + 32]
        mov     qword ptr [rbx - 32768], rax
        mov     r15, qword ptr [rcx]
        mov     r14, qword ptr [rcx + 8]
        mov     r12, qword ptr [rcx + 16]
; ││││││└
; ││││││ @ subarray.jl:28 within `SubArray' @ subarray.jl:38
; ││││││┌ @ subarray.jl:388 within `compute_offset1'
; │││││││┌ @ abstractarray.jl:109 within `axes1'
; ││││││││┌ @ abstractarray.jl:89 within `axes'
; │││││││││┌ @ range.jl:515 within `size'
        movabs  rax, offset length
        mov     rdi, rcx
        vzeroupper
        call    rax
; │└└└└└└└└└
; │┌ @ broadcast.jl:891 within `materialize!' @ broadcast.jl:894
; ││┌ @ subarray.jl:445 within `axes'
; │││┌ @ subarray.jl:450 within `_indices_sub'
; ││││┌ @ abstractarray.jl:113 within `unsafe_indices'
; │││││┌ @ range.jl:555 within `unsafe_length'
; ││││││┌ @ int.jl:86 within `-'
        mov     rax, r12
        sub     rax, r15
; ││││││└
; ││││││┌ @ int.jl:87 within `+'
        add     rax, r14
        movabs  rcx, -9223372036854775808
; ││││││└
; ││││││┌ @ int.jl:261 within `div'
        xor     rcx, rax
        mov     rax, r14
        not     rax
        or      rax, rcx
        setne   al
        test    r14, r14
        je      L316
        test    al, al
        je      L316
; ││└└└└└
; ││ @ broadcast.jl:891 within `materialize!' @ int.jl:0
        lea     rsi, [rsp + 48]
        mov     qword ptr [rsp + 56], r13
; ││ @ broadcast.jl:891 within `materialize!' @ broadcast.jl:894
; ││┌ @ broadcast.jl:944 within `copyto!'
        mov     qword ptr [rsp + 72], r13
        mov     qword ptr [rsp + 80], r15
; │└└
; │┌ @ broadcast.jl:1212 within `dotview'
; ││┌ @ views.jl:133 within `maybeview'
; │││┌ @ subarray.jl:178 within `view'
; ││││┌ @ subarray.jl:209 within `unsafe_view'
; │││││┌ @ subarray.jl:28 within `SubArray' @ subarray.jl:38
; ││││││┌ @ subarray.jl:388 within `compute_offset1'
; │││││││┌ @ int.jl:86 within `-'
        sub     r15, r14
; │└└└└└└└
; │┌ @ broadcast.jl:891 within `materialize!' @ broadcast.jl:894
; ││┌ @ broadcast.jl:944 within `copyto!'
        mov     qword ptr [rsp + 88], r14
        mov     qword ptr [rsp + 96], r12
        mov     qword ptr [rsp + 104], r15
        mov     qword ptr [rsp + 112], r14
        movzx   ecx, byte ptr [rsp + 12]
        movabs  rax, offset "fill!"
        lea     rdi, [rsp + 120]
        lea     rdx, [rsp + 72]
        call    rax
; │└└
        mov     rax, qword ptr [rsp + 120]
        mov     rcx, qword ptr [rsp + 16]
        mov     qword ptr [rcx], rax
        vmovups ymm0, ymmword ptr [rsp + 120]
        vmovups ymm1, ymmword ptr [rsp + 136]
        mov     rax, qword ptr [rsp + 24]
        vmovups ymmword ptr [rax + 16], ymm1
        vmovups ymmword ptr [rax], ymm0
        mov     rcx, qword ptr [rsp + 40]
        mov     qword ptr [rbx - 32768], rcx
        lea     rsp, [rbp - 40]
        pop     rbx
        pop     r12
        pop     r13
        pop     r14
        pop     r15
        pop     rbp
        vzeroupper
        ret
; │┌ @ broadcast.jl:891 within `materialize!' @ broadcast.jl:894
; ││┌ @ subarray.jl:445 within `axes'
; │││┌ @ subarray.jl:450 within `_indices_sub'
; ││││┌ @ abstractarray.jl:113 within `unsafe_indices'
; │││││┌ @ range.jl:555 within `unsafe_length'
; ││││││┌ @ int.jl:261 within `div'
L316:
        movabs  rax, offset jl_throw
        movabs  rdi, offset jl_system_image_data
        call    rax
        nop     word ptr cs:[rax + rax]
; └└└└└└└
```
</details>

It seems that Julia is able to generate some vectorized instructions when using the `.=` broadcasting assignment versus having to do an actual loop.
Taking a skim through the [bitarray.jl](https://github.com/JuliaLang/julia/blob/master/base/bitarray.jl) source code, it seems that they have some auxiliary functions that copy chunks around instead of manually setting bits when broadcasting?  Something close to that.

**Comment by tjol** [comment]
@louie-github Thank you very much for chiming in!

That's very interesting, but I'm pretty sure that's not it: I don't see a significant difference between the two functions' performance. If anything, the for loop is slightly faster!

```jl
setrange(arr, r, i) = @inbounds arr[r] .= i

function setrange2(arr, r,  v)
    for ind in r
        @inbounds arr[ind] = v
    end
end

function benchmark1()
    for _ in 1:1000
        x = trues(10000000);
        setrange(x, 1:7:9900000, false)
    end
end

function benchmark2()
    for _ in 1:1000
        x = trues(10000000);
        setrange2(x, 1:7:9900000, false)
    end
end

precompile(benchmark1, ())
precompile(benchmark2, ())

@time benchmark1()
@time benchmark2()
```

Result for me:
```
  1.225572 seconds (3.00 k allocations: 1.164 GiB, 1.21% gc time)
  1.163060 seconds (3.00 k allocations: 1.164 GiB, 0.43% gc time)
```

**Comment by tjol** [comment]
Got it! This version is ever so slightly faster still than the vectorized version:

```jl
for idx in div(factor*3+1,2):div(factor*2+1,2):div(sieve.sieveSize+1,2)
    @inbounds sieve.rawbits[idx] = false
end
```

Plus the change to the type from #397.

The higher performance of both the above and the vectorized version appears to be a combination of three things:

 * No type checking in the loop when we know it's a `BitVector`
 * No bounds checking in the loop when we use `@inbounds` or the vectorized version
 * No arithmetic to calculate the index in the loop if we use the correct range. (exacerbated by the fact that `Int((num+1)/2)` is slower than `div(num+1, 2)`)

**Comment by tjol** [comment]
Anyway, kudos to @JoelTrent and @lungben for identifying the optimization potential in tweaking how the array is accessed here!

**Comment by rbergen** [comment]
Tagging @dcbi as this PR also targets his original solution.

@lungben could you indicate if you're okay with this PR rolling up #397? We can't merge both without a merge conflict.

**Comment by lungben** [comment]
Sure!

**Comment by rbergen** [comment]
@lungben Thank you! Then, as soon as you feel your improvements have been appropriately added to this PR, please close #397.

**Comment by JoelTrent** [comment]
Nice one @tjol! I didn't think to check changing the range used within the for loop. Stoked that the for loop version can hit equivalent/faster speeds than the vectorised version.

**Comment by dcbi** [comment]
Sorry for missing the past couple tags. I haven't looked at this for a
while. But I love the investigation that's been going on! Very interesting.

**Comment by lungben** [comment]
The change of #397  is not yet in here as far as I can see.
Please feel free to include it, then I'll be happy to close #397.

```
struct prime_sieve
	sieveSize::Int
	rawbits::BitVector # was BitArray before
end
```

**Comment by rbergen** [comment]
Is this PR stable?

**Comment by JoelTrent** [comment]
> Is this PR stable?

Hi @rbergen, I've just committed the changes from @tjol and @lungben that were discussed above. It is now stable

**Comment by louie-github** [comment]
Sorry to bother as the PR seems stable as-is, but, couldn't you also annotate the for loop with `@simd`? I know that on some machines, especially older ones, it might be slower, but on modern CPUs it might give a speedup.

I think it's also safe to use on a BitVector since it doesn't assume that there are no loop-carried memory dependencies. To my knowledge, it would only be unsafe if you use `@simd ivdep`.

**Pull request merged**
