### PR TITLE
fix to Batch solution 2 to include ',' as a delimiter

### PR DESCRIPTION
**Pull request by Richhoef**
## Description
The previous version gave a `Missing operand.` error when it was run. The addition of `,` as a delimiter fixes this. 

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@Richhoef I presume you're running the solution under a non-English locale? Or more accurately, a locale with a number format that uses a comma as the decimal separator?

**Comment by Richhoef** [comment]
Yes, that is true. Since the period is also a delimiter and it didn't seem to give me a problem, I would assume the comma won't give a problem with English locales (but I could be wrong off course)..

**Comment by rbergen** [comment]
@Richhoef I didn't mean to imply that the inclusion of the comma as a delimiter could cause a problem for locales that use a decimal point. I was just trying to establish what problem the PR is solving. :)

**Comment by Richhoef** [comment]
@rbergen Ah ok :)

**Pull request merged**
