### PR TITLE
Add Haskell implementation

### PR DESCRIPTION
**Pull request by fatho**
Just as the title says, adds a Haskell implementation of the sieve.
The benchmark results from my machine are in the readme.

### CODE REVIEW

**Comment by fatho** [comment]
@rhbvkleef The meaning of `stl-unfaithful` is "lack of bitsets" I assume? In any case, I added a variants using a bit set to this implementation as well.

**Comment by rbergen** [comment]
@fatho We are still happy to work towards including your solution in the drag-race; we don't yet have a Haskell implementation in the repo. However, to be able to do so, it would need to comply with the [contribution guidelines](https://github.com/PlummersSoftwareLLC/Primes/blob/drag-race/CONTRIBUTING.md). That also means that the PR needs to be opened on the drag-race branch of this repo, not original (formerly main).

**Comment by fatho** [comment]
@rbergen I finally found the time to (hopefully) make this PR conform with the updated rule set.

**Comment by rbergen** [comment]
@fatho Thank you for taking the time for this. I'll review the solution when I have the time to do so.

**Review by rbergen — APPROVED** [review]
LGTM. I'm happy that we can finally add this. :)

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
