### PR TITLE
Added D solution

### PR DESCRIPTION
**Pull request by eagerestwolf**
## Description

I'm back, this time in D. Let me just say, the performance of D is staggering compared to Dart. I think I have found one of my new favorite languages. I'll let the numbers speak for themselves, but it's impressive. Darn close to C++. Sadly, there will be one more commit. I forgot my Dockerfile was using Ubuntu 21.04 instead of 20.04 while I was troubleshooting an issue, so I need to change that back. Dang it, I almost got everything in one commit.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct category folder.
* [x] I added a README.md or Dockerfile.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by eagerestwolf** [comment]
I'll also be forthcoming and say I've only really got one more in me, but it's a doozy and it's gonna take a while...Objective-C, man that language is so obtuse.

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by rbergen** [comment]
> Objective-C, man that language is so obtuse.

In 2015 I joined a company that did a lot of native mobile app development. I blessed the day when we were able to make the decision to switch from Objective-C to Swift for iOS.

**Comment by marghidanu** [comment]
LGTM

**Pull request merged**
