### PR TITLE
TeX solution_2: add faster wheels

### PR DESCRIPTION
**Pull request by jfbu**
## Description

Faster partially out-rolled wheels to optimize assignment speed.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@jfbu Could you please sync your fork with this branch? It should enable CI for your PR.

**Comment by jfbu** [comment]
@rbergen I merged the drag-race branch, is that what you hinted at? (I also pushed the updated drag-race branch to my fork).

**Comment by rbergen** [comment]
> @rbergen I merged the drag-race branch, is that what you hinted at? (I also pushed the updated drag-race branch to my fork).

@jfbu That's what I meant. Thank you,

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
