### PR TITLE
Python: Use python's count function and normal time.

### PR DESCRIPTION
**Pull request by wgaylord**
The time module works exactly like C#'s time stuff, looks a lot simpler. 

Python has a built-in count function for arrays.

time.time() returns the current time in seconds as a float.

### CODE REVIEW

**Comment by wgaylord** [comment]
On my system using count instead of summing managed to pull out about 10 more passes. (I have a  i7-6700K in my laptop.)

**Comment by dasper** [comment]
I am getting about the same results on my machine running Python 3.8.5.

**Comment by wgaylord** [comment]
Interesting, I am also using Python 3.8, I wonder what could have caused it to increase by 10 passes when I did this initially, as if it truly made it faster then it shouldn't matter who runs it.

**Comment by rbergen** [comment]
I think that, from a perspective of sieve run performance, these changes are basically cosmetic. For that reason, I'm closing this.

**Pull request closed without merging**
