### PR TITLE
faster zig solution

### PR DESCRIPTION
**Pull request by ityonemo**
## Description
Ziglang faster, single-threaded

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right category badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by ManDeJan** [comment]
Hi, I'd be interested in the benchmarks for this on your system :-)
For me this is slower than the devblok's original solution and my own pull request (https://github.com/PlummersSoftwareLLC/Primes/pull/196) I get (12800 vs 14000 vs 14500) iterations respectively. I'm using a amd 3700x at 4.1 GHz on windows.

**Comment by ityonemo** [comment]
I get `zig-ityonemo;7373;5.00028;1`
and `devblok;6100;5.00062;1`

Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz, linux

I just realized I forgot to set the dockerfile to release-fast.  I don't use containers much these days =D...  was just blindly copying devblok's

**Comment by ityonemo** [comment]
should we collab on figuring it out?  I think I can look through your code and see if it improves what I have

**Comment by rbergen** [comment]
@ityonemo and @ManDeJan, if you can collaborate towards one second Zig solution then that would in fact be ideal. 

If that doesn't turn out to be possible, then one thing that would need to be addressed is that both PRs now claim the solution_2 directory under PrimeZig. Stating first that this is completely understandable, we obviously can't merge two solutions in the same solution directory.

**Comment by ManDeJan** [comment]
I'd love to collaborate on this, for now I added your sieve to my benchmarking branch (https://github.com/ManDeJan/Primes/tree/zig-bench/PrimeZig/solution_2)

This yields the following results on my system:
```
Bit set                   , Passes: 12101, Time: 5.00010, Avg: 0.00041, Limit: 1000000
Ityonemo Sieve:           , Passes: 12782, Time: 5.00019, Avg: 0.00039, Limit: 1000000
Regular Sieve Type: bool  , Passes: 14423, Time: 5.00026, Avg: 0.00035, Limit: 1000000
Regular Sieve Type: u1    , Passes: 14470, Time: 5.00030, Avg: 0.00035, Limit: 1000000
Regular Sieve Type: u8    , Passes: 14533, Time: 5.00013, Avg: 0.00034, Limit: 1000000
Regular Sieve Type: usize , Passes:  8663, Time: 5.00019, Avg: 0.00058, Limit: 1000000
Regular Sieve Type: bool  , Passes: 14098, Time: 5.00031, Avg: 0.00035, Limit: 1000000
Regular Sieve Type: u1    , Passes: 14097, Time: 5.00032, Avg: 0.00035, Limit: 1000000
Regular Sieve Type: u8    , Passes: 14604, Time: 5.00001, Avg: 0.00034, Limit: 1000000
Regular Sieve Type: usize , Passes:  6052, Time: 5.00021, Avg: 0.00083, Limit: 1000000
Regular Sieve Type: u16   , Passes: 12544, Time: 5.00026, Avg: 0.00040, Limit: 1000000
Regular Sieve Type: u32   , Passes: 10820, Time: 5.00039, Avg: 0.00046, Limit: 1000000
Regular Sieve Type: u64   , Passes:  8755, Time: 5.00003, Avg: 0.00057, Limit: 1000000
Unrolled Sieve Type: bool , Passes: 14448, Time: 5.00001, Avg: 0.00035, Limit: 1000000
Unrolled Sieve Type: u1   , Passes: 14508, Time: 5.00005, Avg: 0.00034, Limit: 1000000
Unrolled Sieve Type: u8   , Passes: 14424, Time: 5.00013, Avg: 0.00035, Limit: 1000000
Unrolled Sieve Type: usize, Passes:  8526, Time: 5.00047, Avg: 0.00059, Limit: 1000000
Unrolled Sieve Type: bool , Passes: 14012, Time: 5.00007, Avg: 0.00036, Limit: 1000000
Unrolled Sieve Type: u1   , Passes: 14101, Time: 5.00008, Avg: 0.00035, Limit: 1000000
Unrolled Sieve Type: u8   , Passes: 14455, Time: 5.00022, Avg: 0.00035, Limit: 1000000
Unrolled Sieve Type: usize, Passes:  5997, Time: 5.00074, Avg: 0.00083, Limit: 1000000
Unrolled Sieve Type: u16  , Passes: 12399, Time: 5.00003, Avg: 0.00040, Limit: 1000000
Unrolled Sieve Type: u32  , Passes: 10723, Time: 5.00040, Avg: 0.00047, Limit: 1000000
Unrolled Sieve Type: u64  , Passes:  8743, Time: 5.00054, Avg: 0.00057, Limit: 1000000
```
again my system is running an AMD Ryzen @ 4.1GHz, I'd love to see some results from other systems 😃

**Comment by ManDeJan** [comment]
I've managed to run it on a raspberry pi 4B and my phone (snapdragon 845) which yields the following (very interesting) results
## Raspberry Pi 4B
```
Bit set                   , Passes:  1975, Time: 5.00231, Avg: 0.00253, Limit: 1000000
Ityonemo Sieve:           , Passes:  2284, Time: 5.00185, Avg: 0.00219, Limit: 1000000
Regular Sieve Type: bool  , Passes:   573, Time: 5.00348, Avg: 0.00873, Limit: 1000000
Regular Sieve Type: u1    , Passes:   573, Time: 5.00247, Avg: 0.00873, Limit: 1000000
Regular Sieve Type: u8    , Passes:   573, Time: 5.00264, Avg: 0.00873, Limit: 1000000
Regular Sieve Type: usize , Passes:    97, Time: 5.00410, Avg: 0.05159, Limit: 1000000
Regular Sieve Type: bool  , Passes:   515, Time: 5.00875, Avg: 0.00973, Limit: 1000000
Regular Sieve Type: u1    , Passes:   515, Time: 5.00477, Avg: 0.00972, Limit: 1000000
Regular Sieve Type: u8    , Passes:   569, Time: 5.00164, Avg: 0.00879, Limit: 1000000
Regular Sieve Type: usize , Passes:    96, Time: 5.04733, Avg: 0.05258, Limit: 1000000
Regular Sieve Type: u16   , Passes:   182, Time: 5.01098, Avg: 0.02753, Limit: 1000000
Regular Sieve Type: u32   , Passes:   128, Time: 5.01722, Avg: 0.03920, Limit: 1000000
Regular Sieve Type: u64   , Passes:    96, Time: 5.02223, Avg: 0.05231, Limit: 1000000
Unrolled Sieve Type: bool , Passes:   568, Time: 5.00407, Avg: 0.00881, Limit: 1000000
Unrolled Sieve Type: u1   , Passes:   568, Time: 5.00627, Avg: 0.00881, Limit: 1000000
Unrolled Sieve Type: u8   , Passes:   572, Time: 5.00829, Avg: 0.00876, Limit: 1000000
Unrolled Sieve Type: usize, Passes:    98, Time: 5.04110, Avg: 0.05144, Limit: 1000000
Unrolled Sieve Type: bool , Passes:   511, Time: 5.00791, Avg: 0.00980, Limit: 1000000
Unrolled Sieve Type: u1   , Passes:   514, Time: 5.00175, Avg: 0.00973, Limit: 1000000
Unrolled Sieve Type: u8   , Passes:   573, Time: 5.00453, Avg: 0.00873, Limit: 1000000
Unrolled Sieve Type: usize, Passes:    95, Time: 5.01650, Avg: 0.05281, Limit: 1000000
Unrolled Sieve Type: u16  , Passes:   179, Time: 5.00422, Avg: 0.02796, Limit: 1000000
Unrolled Sieve Type: u32  , Passes:   127, Time: 5.03095, Avg: 0.03961, Limit: 1000000
Unrolled Sieve Type: u64  , Passes:    98, Time: 5.04843, Avg: 0.05151, Limit: 1000000
```

## Snapdragon 845
```
Bit set                   , Passes:  4082, Time: 5.00091, Avg: 0.00123, Limit: 1000000
Ityonemo Sieve:           , Passes:  3658, Time: 5.00121, Avg: 0.00137, Limit: 1000000
Regular Sieve Type: bool  , Passes:  2564, Time: 5.00112, Avg: 0.00195, Limit: 1000000
Regular Sieve Type: u1    , Passes:  2569, Time: 5.00162, Avg: 0.00195, Limit: 1000000
Regular Sieve Type: u8    , Passes:  2570, Time: 5.00119, Avg: 0.00195, Limit: 1000000
Regular Sieve Type: usize , Passes:   439, Time: 5.00201, Avg: 0.01139, Limit: 1000000
Regular Sieve Type: bool  , Passes:  2455, Time: 5.00063, Avg: 0.00204, Limit: 1000000
Regular Sieve Type: u1    , Passes:  2449, Time: 5.00000, Avg: 0.00204, Limit: 1000000
Regular Sieve Type: u8    , Passes:  2563, Time: 5.00106, Avg: 0.00195, Limit: 1000000
Regular Sieve Type: usize , Passes:   399, Time: 5.01134, Avg: 0.01256, Limit: 1000000
Regular Sieve Type: u16   , Passes:  1862, Time: 5.00121, Avg: 0.00269, Limit: 1000000
Regular Sieve Type: u32   , Passes:  1021, Time: 5.00318, Avg: 0.00490, Limit: 1000000
Regular Sieve Type: u64   , Passes:   460, Time: 5.00979, Avg: 0.01089, Limit: 1000000
Unrolled Sieve Type: bool , Passes:  2545, Time: 5.00197, Avg: 0.00197, Limit: 1000000
Unrolled Sieve Type: u1   , Passes:  2549, Time: 5.00048, Avg: 0.00196, Limit: 1000000
Unrolled Sieve Type: u8   , Passes:  2552, Time: 5.00133, Avg: 0.00196, Limit: 1000000
Unrolled Sieve Type: usize, Passes:   463, Time: 5.01039, Avg: 0.01082, Limit: 1000000
Unrolled Sieve Type: bool , Passes:  2460, Time: 5.00137, Avg: 0.00203, Limit: 1000000
Unrolled Sieve Type: u1   , Passes:  2464, Time: 5.00193, Avg: 0.00203, Limit: 1000000
Unrolled Sieve Type: u8   , Passes:  2552, Time: 5.00007, Avg: 0.00196, Limit: 1000000
Unrolled Sieve Type: usize, Passes:   437, Time: 5.00868, Avg: 0.01146, Limit: 1000000
Unrolled Sieve Type: u16  , Passes:  1833, Time: 5.00260, Avg: 0.00273, Limit: 1000000
Unrolled Sieve Type: u32  , Passes:  1098, Time: 5.00549, Avg: 0.00456, Limit: 1000000
Unrolled Sieve Type: u64  , Passes:   426, Time: 5.00513, Avg: 0.01175, Limit: 1000000
```

**Comment by ityonemo** [comment]
I think the RPi and Snapdragon results have everything to do with cache invalidation.  Since my solution has 1/2 as many slots (I don't store even numbers) it should cross fewer cache boundaries.  I bet that's why the ryzen does so well not caring, it has 64MB of L3 cache, which means that there are only 16 cache invalidation events across the test set, and I wouldn't be surprised if AMD were doing something really smart with its cache management (versus my older intel which is probably not as optimized).  Are there other differences between what we're doing?

By contrast, there is a shared 2MB L3 cache for the Snapdragon, and 1MB L2 cache for the RPI4B

**Comment by ityonemo** [comment]
I bet if you implement the tighter loop with half as many slots you will see an improvement across the board on yours, it looks like you have far more other optimizations that look really nice (plus the ability to trivially test other types) so why don't I axe my PR and defer to your solution.  I think the places where my stuff is not as good is I wasn't sure if I should be passing some of the slices by pointer or not.

**Comment by ManDeJan** [comment]
That's a very sound explanation of the results I'm getting, that must be why BitSet also performs so well on these smaller cache platforms. I'll look into merging the optimizations you did and run the benchmarks again later tonight if I have time!

**Comment by ManDeJan** [comment]
Some preliminary results but applying your optimizations to my sieve gets it to 18000+ iterations on my machine, thats really impressive! Nice work :)

**Comment by ityonemo** [comment]
ok, I'm going to close this solution on my side in favor of yours...  I have some ideas on how to do parallel, but there are way too many choices!  Ha.  I'm going to maybe work on a naive parallel implementation, and a task-stealing parallel implementation, but probably won't get to it till tomorrow or thursday.

**Pull request closed without merging**
