### PR TITLE
ziglang-multithreaded

### PR DESCRIPTION
**Pull request by ityonemo**
## Description
zig with a bunch of composable optimizations

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
When I saw the title I got confused a little bit, this PR deserves a better title. :)

**Comment by rbergen** [comment]
@ityonemo I agree with @marghidanu that it would be helpful to rename the PR to something that at least includes Zig :)

Furthermore, I was wondering how this PR relates to #200, and even more so #196? As I understood it, @ManDeJan and yourself were collaborating on the latter, at some point. Could you give some insight in this?

**Comment by ityonemo** [comment]
yes.  So the implementation in https://github.com/PlummersSoftwareLLC/Primes/pull/200 was buggy and had some errors (one of was not calculating primes correctly).  This PR incorporates everything we learned along the way, adds a few more optimizations (like wheel), and refactors it in a way to be very clean and composable.  The dockerfile has been redone from scratch and now uses Zig 0.8.0

**Comment by ityonemo** [comment]
I should probably figure out how to get the dockerfile working for arm64

**Comment by rbergen** [comment]
> yes. So the implementation in #200 was buggy and had some errors (one of was not calculating primes correctly). This PR incorporates everything we learned along the way, adds a few more optimizations (like wheel), and refactors it in a way to be very clean and composable. The dockerfile has been redone from scratch and now uses Zig 0.8.0

Does this mean that #200 is no longer intended to be merged? If so, I would suggest that #200 is closed, and the solution in this PR is changed to become PrimeZig/solution_2.

**Comment by ityonemo** [comment]
can do.

**Comment by rbergen** [comment]
> can do.

My apologies for the confusion, but when I spoke about #200 in my last comment, I meant #196. Will that be closed, too, or is this PR now separate from your collaboration with @ManDeJan on #196?

**Comment by ityonemo** [comment]
It's still a collaboration, but its sufficiently different from #2 to have warranted a new number.  I'm not comfortable with the work I did on #2 (multithreaded part).  I think I messed up deleting it, I thought the contents of #2 were solely my multithreaded things

**Comment by ityonemo** [comment]
I'm going to close this PR and cherry pick corrections and re-PR.

**Pull request closed without merging**
