### PR TITLE
Adding wheel sieve Rust implementation

### PR DESCRIPTION
**Pull request by SergioCKS**
## Description

This is a  Rust implementation of a wheel-based algorithm for generating primes.

When I saw the `algorithm:wheel` badge I felt intrigued about wheel sieve variations for prime generation, as wheel-based solutions seem to be quite a bit faster than those using the base algorithm. Seeing that Rust didn't had a wheel-based solution I decided to give it a shot. After much reading, coding and testing, this is the result.

I understand that the algorithm used deviates substantially from the base Erathostenes sieve algorithm, however, the core of the algorithm still relies on sieving primes. In fact, after the first phase of the algorithm (wheel generation), a regular sieve is used.

## Contributing requirements

This implementation differs substantially from all other Rust implementation (and quite possibly from almost all other implementations as well).

I checked the open pull requests and there doesn't seem to be another wheel-based solution for Rust.

The performance of this implementation could potentially be higher than most other Rust solutions.

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by ItalyToast** [comment]
@SergioCKS before a maintainer comes and checks your PR you should probably fix your markdown checkboxes: replace "[ x]" with [x]. It will show that you have done all the tasks in the PR list.

**Comment by SergioCKS** [comment]
@ItalyToast thanks, didn't notice that 😅

**Comment by rbergen** [comment]
@SergioCKS Just for clarity, could you indicate in your README and your output line label which wheel you're using? Is it 2 of 6, 8 of 30, 48 of 210, ...?

**Comment by SergioCKS** [comment]
@rbergen I added a high level algorithm description to the README. The implementation doesn't use a specific wheel of fixed size, instead it construct the largest wheel possible based on the desired limit.

**Comment by rbergen** [comment]
@SergioCKS Thanks for clarifying this.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
