### PR TITLE
Modifications for a faster and more faithful implementation of

### PR DESCRIPTION
**Pull request by johandweber**
Solution_1 for Fortran.

This solution corresponds to the original pull request by @tjol ,
but was modified such that consistently 64bit integers are used
and the memory for the sieve is allocated and deallocated for
each run, which makes the soulution more faithful when compared to my 
previous solution.

@tjol gave me the permission to release to code under joint ownership
and we are willing to provide the source code using the BSD-3 license.

Furthermore I made some corrections to README.md.

Note that the I have changed the file suffix of the source file from
f03 to f08, because the int64, and in8 are only required to be 
included in the iso_fortran_env module since Fortran 2008.

* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by tjol** [comment]
Looks like you forgot to delete the `.f03` file and to push your changes to the README and Dockerfile. :-)

**Comment by johandweber** [comment]
Thanks, I am not very experienced with git.. 
Now I have updated my pull request.

**Comment by rbergen** [comment]
@johandweber and @tjol please indicate when you agree that this PR is ready for review.

**Comment by johandweber** [comment]
I think now it is ready for review.

**Comment by tjol** [comment]
Looks good to me!

**Review by rbergen — APPROVED** [review]
LGTM

**Pull request merged**
