### PR TITLE
CPP single-threaded implementation

### PR DESCRIPTION
**Pull request by Destroyerrrocket**
[from the first commit]
I've explicitly not used constexpr shennanigans that would go against
the spirit of the competition, or used intrinsics that would pretty much
ruin the fun of the game. I've seen that there's already someone that
has provided an implementation at compile time, so I feel that the power
of C++ already showcased ;D

I also wanted to see how the alignment of the underlying data would
affect the performance. It has been a pretty cool afternoon experiment,
showing that 32-bits was the sweet spot in my machine.

## Description
Hey! When I saw the implementation of the C++ version I saw there was 
a bit of room for improvement, so in order to defend my favorite language,
I decided to mess around a bit with this project.

I originally planned on making a fully compile time implementation, but I 
soon saw that it went against the faithfulness of the race. Since there was 
already one pull request in the works, I decided to just throw my hat at a 
simple runtime one.
 
## Contributing requirements

* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by Destroyerrrocket** [comment]
~~I clicked publish too early, one second please~~
Done!

**Comment by rbergen** [comment]
Would I be right in concluding from the structure of the PrimeCPP.cpp file that you're really seeking to improve the performance of the existing PrimeCPP/solution_1 implementation? In that case I think it would be better to change your PR to one that indeed modifies that implementation. Dave, for one, prefers that if the fundamental characteristics of the implementation (algorithm, faithfulness, bits per prime, ...) stay the same.

**Comment by Destroyerrrocket** [comment]
If you'd prefer for me to modify solution_1, I'd gladly do so. I can move it immediately.

**Comment by rbergen** [comment]
I think it may indeed be best to open a PR that seeks to modify solution_1. We will of course still review your proposal and ask the author of the original implementation for a review, as well. :)

**Pull request closed without merging**
