### PR TITLE
Added implementation in C with segmented algorithm

### PR DESCRIPTION
**Pull request by fvbakel**
## Description
Added implementation in C with segmented algorithm. See README.md for more details. I assume the algorithm is `other`. However I am not sure, it could also be `base` depending on how flexible you read the rules for the base algorithm.

## Contributing requirements
* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by fvbakel** [comment]
Just realize that this code has the same bug as mentioned in PR #406. Mmm, will fix that in the weekend.

**Comment by fvbakel** [comment]
Solved the bug mentioned in PR #406 in this solution and took the opportunity to implement further optimizations and solve other bugs in this solution. 

For the memory allocation I used the statement below to allow just complete words. I think that is simpler and more fail save compared to what is proposed in PR #406.

```C
#ifdef COMPILE_64_BIT
#define TYPE uint64_t
#define MASK 63U
#define SHIFT 6U
#define MEMSHIFT 7U
#else
#define TYPE uint32_t
#define MASK 31U 
#define SHIFT 5U
#define MEMSHIFT 6U
#endif
...
  sieve_state->nr_of_words=(limit >> MEMSHIFT) + 1;
  sieve_state->bit_array=calloc(sieve_state->nr_of_words,sizeof(TYPE));
...
```

**Comment by fvbakel** [comment]
@rbergen Sorry for the extra commits and bug solving in this PR. It should be ready for review now.

**Review by rbergen — APPROVED** [review]
The algorithm is correctly labeled as `other`. And with that label set as it is, it looks good to me.

**Comment by fvbakel** [comment]
I found one small bug in the the calculation at step 3 and took that opportunity to do cleanup two other small things too. Sorry, this will be my last update on this PR. I hope :-).

**Review by rbergen — APPROVED** [review]

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
