### PR TITLE
100%+ Performance improvement for PrimeCSharp/solution_2

### PR DESCRIPTION
**Pull request by ItalyToast**
## Description
100%+ performance improvement to daves original implementation for C#. (When run under .net core 3.1)

I dont think it needs its own solution so I made the following performance improvements to daves code:

Manual inlining of GetBit and SetBit in the tight loop.
Renaming bitArray to oddNumbersBitArray for clarity.
Marking oddNumbersBitArray readonly to enable the compiler to cache the pointer.
Using BitArray.Count instead of sieveSize so the compiler can more easily remove bound checks.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [ ] I placed my solution in the correct solution folder.
* [ ] I added a README.md with the right badge(s).
* [ ] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
@ItalyToast Thanks for your submission, I think there are some good improvements in here.
However, I will have to ask you to please revert the rename of bitArray to oddNumbersBitArray. Dave has indicated that he welcomes changes that improve performance, but likes those to be applied with as few "collateral" changes as possible.

**Comment by ItalyToast** [comment]
I wanted to change the name since the inlining changes your mental model of the code. The old GetBit function does the divide by two so you can think of num as a real number but with the inlining it makes more sense to think of num as an "oddnumber index" into the bitarray and thats why it became oddNumbersBitArray. I could revert the name change and/or maybe add some kind of better comment.

**Comment by rbergen** [comment]
I understand your reasoning, but this repo is a mix of a large number of solutions/implementations that in part do, and in part do not divide by two, without making that explicit in the naming of the array. I think you can therefore safely revert the name change, and don't need to worry about commenting to explain.
Most people will look at the code as it is at the time they look at it. It's therefore not necessary to explain the differences between the current state of the code and a previous iteration of it.

**Comment by ItalyToast** [comment]
that makes sense, will revert the name change then.

**Pull request merged**
