### PR TITLE
Optimizations for PrimeCPP

### PR DESCRIPTION
**Pull request by supsm**
## Description

adds a few optimizations which improve performance (13% faster on my machine)  
not sure why the diff is messed up, I might've accidentally changed some indentation  
**IMPORTANT:** I have not applied these optimizations to multithreaded since it doesn't seem to perform as well. I have also decided not to mess with constexpr solution.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [ ] I added a README.md with the right badge(s). **(does not apply)**
* [ ] I added a Dockerfile that builds and runs my solution. **(does not apply)**
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
For some reason (line ends? whitespacing?) the diff makes it look like the whole file has changed, which it clearly hasn't. Please modify your commit so that the diff only shows the actual changes in code.

**Comment by supsm** [comment]
It should be fixed now, can you check again?

**Comment by rbergen** [comment]
It is fixed. And now it is, I can see that your algorithm effectively skips:
- checking if 5 is a prime
- establishing it is a prime, and 
- clearing multiples of 5

All of this effectively means the algorithm treats 5 as a known prime. That's a deviation of the base algorithm, which makes it's not the base algorithm anymore. 

Based on this, we can't merge this as an optimization to the existing solution.

**Comment by supsm** [comment]
Why would this be any different from skipping multiples of 2?

**Comment by rbergen** [comment]
Because 2 is the _only_ allowed exception. Dave has been very explicit about this up to this point, [including yesterday](https://github.com/PlummersSoftwareLLC/Primes/discussions/318#discussioncomment-972240), and will be again, soon.

**Comment by supsm** [comment]
Alright, thanks!

**Pull request closed without merging**
