### PR TITLE
primes.pl: gate printout behind $show_results

### PR DESCRIPTION
**Pull request by greg-kennedy**
The existing way of doing this was interfering with my profiling output, changed to just a block if() statement instead.

### CODE REVIEW

**Comment by marghidanu** [comment]
I don't see any improvements here.

**Comment by greg-kennedy** [comment]
Profiling with Devel::NYTProf shows 500,000 calls made during the `for` loop that never actually print anything.  This makes the prof. output harder to parse when attempting to do optimization work.

It also spares 1.5 seconds of time doing nothing at the end of the job.

**Comment by marghidanu** [comment]
`print_results` is not part of the benchmark it just prints the results what's the advantage of optimizing this?

**Comment by greg-kennedy** [comment]
because it makes output from devel::nytprof harder to read by adding a ton of noise

**Comment by marghidanu** [comment]
You can also comment on the function since is not relevant to the output while running your profiling.

**Pull request closed without merging**
