### PR TITLE
Emojicode implementation

### PR DESCRIPTION
**Pull request by marghidanu**
## Description

Emojicode implementation

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by marghidanu** [comment]
@rbergen, have fun! :)

**Comment by rbergen** [comment]
Holy crap, Brainf*ck must be the next one up from you :D

**Review by rbergen — APPROVED** [review]
Looks weird to me, but at the same time really seems to work :)

**Comment by fvbakel** [comment]
Wow, compliments!

**Comment by marghidanu** [comment]
It’s a totally faithful implementation

**Comment by rbergen** [comment]
> It’s a totally faithful implementation

Well, in that case, by all means merge the thing!

**Pull request merged**
