### PR TITLE
Slight performance improvement for Julia solution_3

### PR DESCRIPTION
**Pull request by louie-github**
## Description

This might just be a quirk on my machine (so further testing is appreciated!) but, changing one line:
```diff
-@inline _get_chunk_index(i::Integer) = _div_uint_size(i - 1) + 1
+@inline _get_chunk_index(i::Integer) = _div_uint_size(i + (_uint_bit_length - 1))
```
seems to give a significant speedup:
```
# ========== Before implementing change ==========
PS D:\Office Files\Programming\PrimesFork\PrimeJulia\solution_3> julia .\primes_1of2.jl
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 8653 | Elapsed: 5.0 | Passes per second: 1730.6 | Average pass duration: 0.0005778342771293193
louie-github_port_1of2;8653;5.0;1;algorithm=base,faithful=yes,bits=1

PS D:\Office Files\Programming\PrimesFork\PrimeJulia\solution_3> julia .\primes_1of2.jl
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 8625 | Elapsed: 5.0 | Passes per second: 1725.0 | Average pass duration: 0.0005797101449275362
louie-github_port_1of2;8625;5.0;1;algorithm=base,faithful=yes,bits=1

# ========== After implementing change ==========
PS D:\Office Files\Programming\PrimesFork\PrimeJulia\solution_3> julia .\primes_1of2.jl
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 9164 | Elapsed: 5.0 | Passes per second: 1832.8 | Average pass duration: 0.0005456132693147098
louie-github_port_1of2;9164;5.0;1;algorithm=base,faithful=yes,bits=1

PS D:\Office Files\Programming\PrimesFork\PrimeJulia\solution_3> julia .\primes_1of2.jl
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 9255 | Elapsed: 5.0 | Passes per second: 1851.0 | Average pass duration: 0.0005402485143165856
louie-github_port_1of2;9255;5.0;1;algorithm=base,faithful=yes,bits=1

PS D:\Office Files\Programming\PrimesFork\PrimeJulia\solution_3> julia .\primes_1of2.jl
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 9165 | Elapsed: 5.0 | Passes per second: 1833.0 | Average pass duration: 0.0005455537370430987
louie-github_port_1of2;9165;5.0;1;algorithm=base,faithful=yes,bits=1
```

## Contributing requirements

* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
> This might just be a quirk on my machine (so further testing is appreciated!)

Can I deduce from this that you want me to hold on merging this until further notice?

**Comment by louie-github** [comment]
Sorry for the delayed response, but yes, until I get some more information, I'd prefer if you hold off on merging this.

**Comment by louie-github** [comment]
Okay, so correct me if I'm wrong about anything here, but here's what I found:

When turning off `@simd`, as I do below on a Raspberry Pi 3B, the original version wins by a landslide:
```
❯ julia primes_1of2.jl && julia primes_edited.jl
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 1145 | Elapsed: 5.0025248527526855 | Passes per second: 228.88442010836852 | Average pass duration: 0.004369017338648634
louie-github_port_1of2;1145;5.0025248527526855;1;algorithm=base,faithful=yes,bits=1Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 781 | Elapsed: 5.0038368701934814 | Passes per second: 156.08022808501377 | Average pass duration: 0.006406961421502537
louie-github_port_1of2;781;5.0038368701934814;1;algorithm=base,faithful=yes,bits=1
```

However, when I add `@simd` back, it seems to be about even:
```
pi in louie-pi in ~/dev/PrimesTest via ஃ v1.6.2
❯ julia primes_1of2.jl && julia primes_edited.jl
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 874 | Elapsed: 5.005110025405884 | Passes per second: 174.6215359030242 | Average pass duration: 0.005726670509617716
louie-github_port_1of2;874;5.005110025405884;1;algorithm=base,faithful=yes,bits=1
Settings: sieve_size = 1000000 | duration = 5
Number of trues: 78498
primes_1of2.jl: Passes: 874 | Elapsed: 5.004855155944824 | Passes per second: 174.63042840747406 | Average pass duration: 0.005726378896962042
louie-github_port_1of2;874;5.004855155944824;1;algorithm=base,faithful=yes,bits=1
```

My best guess after looking at the `@code_native` output is that the newer version can overflow because of the `+ 63` part and that slows it down. When `@simd` is applied, I'm guessing that it assumes that it will not overflow, and so, can generate faster code.

Though, on my x86_64 machine, the only difference in the generated assembly for `clear_factors!` when `@simd` was applied was `lea     rsi, [rbx - 64]` instead of `mov     rsi, rbx` and `or      qword ptr [rcx + 8*rsi], rdi` instead of `or      qword ptr [rcx + 8*rsi - 8], rdi`. A similar thing happens with `unsafe_find_next_factor_index`. I don't see how that by itself could be faster. 

Testing without `@simd` on said main machine under WSL gave no significant, consistent difference.

Testing on a slower machine showed no significant, consistent difference between the two solutions with `@simd`, but showed similar performance drops with the Raspberry Pi without `@simd`, albeit a bit less dramatic.

Given this information, I'm going to leave this PR open for now and I'll finalize things quietly. I'll just inform when this PR is stable.

Apologies for any inconveniences.

**Comment by louie-github** [comment]
I'm going to close this PR for now; I'll do some more research and incorporate all the small changes, if any, into another PR.
Thanks for your time!

**Comment by louie-github** [comment]
After a lot more investigating, I'm running out of ideas as to how to make the code faster. I think it'd be best if this change was just merged, since I've been able to test it on another machine and speedups were noticed.

I apologize for the indecisiveness.

**Comment by rbergen** [comment]
The primes_edited.jl file doesn't seem to be referenced anywhere within the solution. If this file is a temporary file used while putting your PR together, then please remove it from your commit.

**Comment by louie-github** [comment]
Oops. Very sorry. Will do.

**Pull request merged**
