### PR TITLE
Pin Haskell to 8.10.4 to fix build failure

### PR DESCRIPTION
**Pull request by rbergen**
This pins the Haskell Docker base image to 8.10.4 instead of 8.10. The Haskell image with tag 8.10 got bumped to version 8.10.5, which breaks the build.

The issues reported by hadolint will be fixed with the merge of #711.

### CODE REVIEW

**Comment by Macleykun** [comment]
Heya! Sorry to hear/see that Haskell now starts to misbehave due to the latest haskell:8.10.5 (or later).
Is it an idea that i adjust my pull to use the dockerlint fixed version with the specified 8.10.4?

I did verify the build on my end, and also got the issue, and fixed it: https://pastebin.com/mD0SYUKx

We can either:
- Leave both as is, and that i fix it in a later pr
- Use the dockerlint improved version of this fix in your pr here: https://pastebin.com/QunW91q4
- Or that i put the fix: https://pastebin.com/QunW91q4 in my pr

It's up to you :-) i don't mind either of these options! Thanks for submitting a quick pull for my pull 😅

**Comment by rbergen** [comment]
@Macleykun If you can add the fix to your PR (which has already been reviewed) then I can merge it in with the rest of that. In that case I'll close this one.

**Comment by rbergen** [comment]
(...just couldn't help noticing that the machine name in your first pastebin snippet has a very Dutch flavour to it, pun intended.)

**Comment by Macleykun** [comment]
> @Macleykun If you can add the fix to your PR (which has already been reviewed) then I can merge it in with the rest of that. In that case I'll close this one.

Done!


> (...just couldn't help noticing that the machine name in your first pastebin snippet has a very Dutch flavour to it, pun intended.)

hehe yep :D was getting bored of naming my machines after the greek alphabet, and like android/nodejs i figured dutch snacks would be a lovely idea :D

**Comment by rbergen** [comment]
Fix was included in #711, that just got merged.

**Pull request closed without merging**
