### PR TITLE
CI QEMU builds

### PR DESCRIPTION
**Pull request by marghidanu**
This should allow building Docker images for various platforms, for now just amd64. Later we can probably add arm64. Also, the jobs should now be listed alphabetically in the CI.

### CODE REVIEW

**Comment by marghidanu** [comment]
Hold the merge, I will also add container scanning.

**Comment by rbergen** [comment]
Fantastic! I'll hold on #186 until we've merged this. I'll then re-enable the Dockerfile in that PR, so we can test this with an actual solution. That also means that we'll then have an arm64 assembly solution in the branch without any missing pieces.

**Comment by marghidanu** [comment]
Ok, let's skip the image scan; for now, I will add that separately on a branch that addresses a few security concerns. Please update your arm64 branch after this merge. We will need to add a special case for it and make sure we build the image using the linux/arm64 platform

**Comment by rbergen** [comment]
> Ok, let's skip the image scan; for now, I will add that separately on a branch that addresses a few security concerns.

Ok. I will review this PR, later today.

> Please update your arm64 branch after this merge. We will need to add a special case for it and make sure we build the image using the linux/arm64 platform

I was wondering about that. Do I need to do anything specific in the arm64 assembly solution Dockerfile or the solution directory to mark it as arm64?

**Comment by marghidanu** [comment]
> I was wondering about that. Do I need to do anything specific in the arm64 assembly solution Dockerfile or the solution directory to mark it as arm64?

We can mark it directly in the CI, if the solution name matches our label then we run the arm64 job otherwise de use the default.

**Comment by rbergen** [comment]
That's certainly a pragmatic approach. I can't suppress the feeling that conceptually I prefer a more "dynamic" approach, but I guess it's okay to worry about that if and when we have more architecture-specific solutions.

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by marghidanu** [comment]
Actually I found my bug for the image scanning configuration and corrected it. Everything works fine, let's merge this and have it available for future builds.

**Comment by rbergen** [comment]
LGTM, again

**Pull request merged**
