### PR TITLE
NodeJS solution with 32bit array and optimizations

### PR DESCRIPTION
**Pull request by rogiervandam**
## Description
NodeJS solution with 32bit array and optimizations

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
The key characteristics of this implementation (algorithm, faithfulness, bits per prime) are the same as those of solution_1, Could you please explain:

- what are the optimizations in this implementation vs solution_1, from a performance perspective?
- what is the improvement in performance numbers is that these optimizations achieve?
- why you chose to open a PR to create a second solution, instead of applying these optimizations to the solution that is already in place?

**Comment by rogiervandam** [comment]
3x to 5x performance gain due to using bit shifting and masking, like the PrimeC solutions.
Als some code restructuring helps in performance, while remaining faithful.
Feels like the restructure is educational in what performance is possible with nodejs (close to c)

**Comment by rbergen** [comment]
@fvbakel It does seem that this implementation is significantly faster than the current PromeNodeJS/solution_1. With the credit that @rogiervandam has given you as the author of one of the solutions his is based on, would you be ok with replacing the current solution_1 with the one in this PR?

**Comment by fvbakel** [comment]
@rogiervandam @rbergen I am perfectly fine with overwriting my solution_1. Great to see this performance improvement!

**Comment by rbergen** [comment]
@fvbakel Thanks for responding so quickly (and supportive, I might add :) )

@rogiervandam Could you modify your PR to replace the existing PrimeNodeJS/solution_1 directory's contents with what it now aims to place in PrimeNodeJS/solution_2?

**Comment by rogiervandam** [comment]
I changed the pull request to make it solution1

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
