### PR TITLE
Change Nim solution_3 to unrolled hybrid...

### PR DESCRIPTION
**Pull request by GordonBGood**
## Description

**Note:**  The included Dockerfile actually builds the Nim compiler from source so that it will work across all platforms; however, if this is considered to be too slow, the race administrators may elect to build a set of custom Docker images including the pre-compiled Nim compiler using the commands from this file and I would change this Dockerfile to `FROM` those images on Docker Hub.

This changes this contribution to use both the old technique of "Extreme Loop Unrolling" for the sparse prime factors and the new technique of "Dense Marking" for base prime factor values below a set threshold; currently the threshold is set to odd primes below 64 for this Nim version.

This is similar to the latest Chapel hybrid version except that it uses Nim's AST macros to extend the capability to larger factors without having to use external code generation.  However, it is fast for the same reasons: it copies the sieve buffer into a register value `v`, then sets the composite multiple bits one by one with static register operations until all bits have been marked in the word for this factor, then commits the 64-bit word to the deliverable sieve buffer, repeating 64-bit words until all words in the modulo pattern are complete, then looping for all patterns across the full sieve buffer.  As the majority of the marking operations are immediate/register operation not requiring memory access, its maximum speed approaches the maximum Instructions per Clock Cycle for the CPU used minus some losses for "cache thrashing".  It is faster than the Chapel version because it has a higher "dense factor" threshold and also likely due to better compiler optimizations.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
We will indeed need a pre-built Nim base image for this. I'm happy to create one and push it to the primeimages Docker Hub account. However, when doing so I will make some changes to the top of the current Dockerfile:

1. I'll switch from Fedora to Ubuntu as the base image for the base image. The main reason is that Fedora essentially requires a continuous application of upgrades (as illustrated by the `dnf upgrade` in the current Dockerfile), which impacts determinism of build output. Another reason is that I am more familiar with Ubuntu, which means that it'll be easier to maintain the image, once built.
2. I'll modify the section that performs the actual Nim build to make it comply with Dockerfile best practices.

If there are any objections to this then please let me know. In that case I won't create and push the Nim base image, and it will have to be built and provided by other means.

**Comment by GordonBGood** [comment]
@rbergen:

> We will indeed need a pre-built Nim base image for this. I'm happy to create one and push it to the primeimages Docker Hub account. However, when doing so I will make some changes to the top of the current Dockerfile:

Yes, changes in my Dockerfile are expected: this version of Dockerfile was just provided to try to help you see how to build the Nim compiler without having to do too much of your own research.

Also, will you be able to support running on arm64 as you were able to do for the Chapel Docker image(s) you built?

> 1. I'll switch from Fedora to Ubuntu as the base image for the base image. The main reason is that Fedora essentially requires a continuous application of upgrades (as illustrated by the `dnf upgrade` in the current Dockerfile), which impacts determinism of build output. Another reason is that I am more familiar with Ubuntu, which means that it'll be easier to maintain the image, once built.

Okay, no problem other than a slight concern over what version of gcc is available on Ubuntu; my testing was with gcc version 11.2 and I suppose an older version might make a slight difference in performance.

> 2. I'll modify the section that performs the actual Nim build to make it comply with Dockerfile best practices.

Yes, that's why I proposed leaving it to you as you have so much more experience in building Docker images.

> If there are any objections to this then please let me know. In that case I won't create and push the Nim base image, and it will have to be built and provided by other means.

No objections other than as expressed regarding the gcc version.  What version is Ubuntu pushing these days?

**Comment by rbergen** [comment]
> No objections other than as expressed regarding the gcc version. What version is Ubuntu pushing these days?

On Ubuntu Hirsute (21.04), GCC 11 is available within the standard package repository: https://packages.ubuntu.com/hirsute/gcc-11. On amd64, that will currently resolve to GCC 11.1. On arm64, to GCC 11.

**Comment by GordonBGood** [comment]
@rbergen:

> > No objections other than as expressed regarding the gcc version. What version is Ubuntu pushing these days?
> 
> On Ubuntu Hirsute (21.04), GCC 11 is available within the standard package repository: https://packages.ubuntu.com/hirsute/gcc-11. On amd64, that will currently resolve to GCC 11.1. On arm64, to GCC 11.

gcc version 11 or so is fine.  Thank you.

**Comment by rbergen** [comment]
> gcc version 11 or so is fine. Thank you.

Alright, cool, I'll see if I can put this together, this weekend.

**Comment by rbergen** [comment]
@GordonBGood The image is available for amd64 and arm64 at https://hub.docker.com/r/primeimages/nim. To use it, you can change your `FROM` directive to 
```dockerfile
FROM primeimages/nim:1.4.8
```

That one line would then effectively replace the first 10 lines of the Dockerfile in this PR. Also note that the `PATH=/nim-lang/nim-1.4.8/bin:$PATH` in the `RUN` directive on line 14 can be dropped again, as in the primeimages/nim image, the Nim binaries are included in the PATH.

**Comment by GordonBGood** [comment]
@rbergen:

> @GordonBGood The image is available for amd64 and arm64 at https://hub.docker.com/r/primeimages/nim. To use it, you can change your `FROM` directive to
> 
> ```dockerfile
> FROM primeimages/nim:1.4.8
> ```
> 
> That one line would then effectively replace the first 10 lines of the Dockerfile in this PR. Also note that the `PATH=/nim-lang/nim-1.4.8/bin:$PATH` in the `RUN` directive on line 14 can be dropped again, as in the primeimages/nim image, the Nim binaries are included in the PATH.

The above changes have been made to the Dockerfile in the PR, tested, and committed.

The speed seems to be at least as fast as before.

Thank you very much for your help.  I see what you've done in the Dockerfile that created the Docker Hub image(s), and I wouldn't have been able to do it so easily, at least in Ubuntu.

Using this as an example, it may be that I can help create new images for the two languages that I would like to be able to run on arm64:  GHC Haskell and Crystal.  It seems that the Haskell images likely need to be based on Debian 10 as it seems that is the only platform on which GHC Haskell for arm64 has been tested, and I've just started to look into how to do it for Crystal.

**Comment by rbergen** [comment]
@GordonBGood

> Thank you very much for your help. I see what you've done in the Dockerfile that created the Docker Hub image(s), and I wouldn't have been able to do it so easily, at least in Ubuntu.

You're welcome. I'm not an expert in any way (for one, I tend to consider @marghidanu's efforts in this area way more elegant than my own), but I guess I know enough to be dangerous. :)

> Using this as an example, it may be that I can help create new images for the two languages that I would like to be able to run on arm64: GHC Haskell and Crystal. It seems that the Haskell images likely need to be based on Debian 10 as it seems that is the only platform on which GHC Haskell for arm64 has been tested, and I've just started to look into how to do it for Crystal.

The Chapel image is also based on Debian 10, so that is not an issue in itself. You could consider opening a PR to modify Haskel and Crystal solutions to use new Dockerfiles that you've composed. If build times are such that pre-built base images are warranted, or there are other reasons to do so, we can then follow an approach similar to the one we used here.

With that said, I'd like to go back to this PR. I've been wondering for a while if it would be possible to get a view on the Nim code that the macros are actually generating. As in, see (some meaningful fragment of) that generated source code. I'm trying to mentally follow the evaluation tree that is put together, and I believe I am able to do so to a sufficient extent to assess that the algorithm it implements is the one you describe. However, I'm not a compiler (I wrote an assembler once, but that's a different story), so there is real chance I'm missing some details that are really worth noticing.

Would the approach to this be uncommenting one or more of the lines between 177 and 179 and then compiling the source?

**Comment by GordonBGood** [comment]
@rbergen:

> With that said, I'd like to go back to this PR. I've been wondering for a while if it would be possible to get a view on the Nim code that the macros are actually generating. As in, see (some meaningful fragment of) that generated source code. I'm trying to mentally follow the evaluation tree that is put together, and I believe I am able to do so to a sufficient extent to assess that the algorithm it implements is the one you describe. However, I'm not a compiler (I wrote an assembler once, but that's a different story), so there is real chance I'm missing some details that are really worth noticing.
> 
> Would the approach to this be uncommenting one or more of the lines between 177 and 179 and then compiling the source?

Yes, as described in the README.md file: "One can see the generated code at compile time for the base prime/step value of three by uncommenting line 178.".  As described, this is for the first "dense" prime value of three.  Above this code the marking has been done one by one to advance to the next successive 64-bit boundary.  Following this code, a new `ndx  next bit index has been set according to the marking in the last of the word patterns, the rest of the marking for the entire sieve buffer is completed bit by bit (there aren't many, just the ones that wouldn't fit in the modulo pattern).  The code for the base prime value of three is as follows:
```amd64
of 3'u8:
  while seta <= endalmt:
    let cptr = cast[ptr UncheckedArray[uint64]](seta)
    var v = cptr[0] or 4'u64
    v = v or 32'u64
    v = v or 256'u64
    v = v or 2048'u64
    v = v or 16384'u64
    v = v or 131072'u64
    v = v or 1048576'u64
    v = v or 8388608'u64
    v = v or 67108864'u64
    v = v or 536870912'u64
    v = v or 4294967296'u64
    v = v or 34359738368'u64
    v = v or 274877906944'u64
    v = v or 2199023255552'u64
    v = v or 17592186044416'u64
    v = v or 140737488355328'u64
    v = v or 1125899906842624'u64
    v = v or 9007199254740992'u64
    v = v or 72057594037927936'u64
    v = v or 576460752303423488'u64
    cptr[0] = v or 4611686018427387904'u64
    v = cptr[1] or 2'u64
    v = v or 2'u64
    v = v or 16'u64
    v = v or 128'u64
    v = v or 1024'u64
    v = v or 8192'u64
    v = v or 65536'u64
    v = v or 524288'u64
    v = v or 4194304'u64
    v = v or 33554432'u64
    v = v or 268435456'u64
    v = v or 2147483648'u64
    v = v or 17179869184'u64
    v = v or 137438953472'u64
    v = v or 1099511627776'u64
    v = v or 8796093022208'u64
    v = v or 70368744177664'u64
    v = v or 562949953421312'u64
    v = v or 4503599627370496'u64
    v = v or 36028797018963968'u64
    v = v or 288230376151711744'u64
    cptr[1] = v or 2305843009213693952'u64
    v = cptr[2] or 1'u64
    v = v or 1'u64
    v = v or 8'u64
    v = v or 64'u64
    v = v or 512'u64
    v = v or 4096'u64
    v = v or 32768'u64
    v = v or 262144'u64
    v = v or 2097152'u64
    v = v or 16777216'u64
    v = v or 134217728'u64
    v = v or 1073741824'u64
    v = v or 8589934592'u64
    v = v or 68719476736'u64
    v = v or 549755813888'u64
    v = v or 4398046511104'u64
    v = v or 35184372088832'u64
    v = v or 281474976710656'u64
    v = v or 2251799813685248'u64
    v = v or 18014398509481984'u64
    v = v or 144115188075855872'u64
    v = v or 1152921504606846976'u64
    cptr[2] = v or 9223372036854775808'u64
    v = cptr[3] or 4'u64
    v = v or 4'u64
    seta += adv
  ndx = ((seta - bitbufa) shl 3) or mod0.int
```
If one changes the index value 1 .. 31 for the base prime values of 3 .. 2 .. 63 you'll see each of the patterns in turn.  There is some special casing for the larger "dense" prime values that may only "hit" a given 64-bit word once in that then no intermediate value is used by the single bit is marked by a single read write modify `or` instruction.  Such a case is, for instance, for the base prime value of 59 (index 29), as follows:
```assembler
of 59'u8:
  while seta <= endalmt:
    let cptr = cast[ptr UncheckedArray[uint64]](seta)
    var v: uint64
    cptr[0] = cptr[0] or 64'u64
    v = cptr[1] or 2'u64
    v = v or 2'u64
    cptr[1] = v or 1152921504606846976'u64
    cptr[2] = cptr[2] or 36028797018963968'u64
    cptr[3] = cptr[3] or 1125899906842624'u64
    cptr[4] = cptr[4] or 35184372088832'u64
    cptr[5] = cptr[5] or 1099511627776'u64
    cptr[6] = cptr[6] or 34359738368'u64
    cptr[7] = cptr[7] or 1073741824'u64
    cptr[8] = cptr[8] or 33554432'u64
    cptr[9] = cptr[9] or 1048576'u64
    cptr[10] = cptr[10] or 32768'u64
    cptr[11] = cptr[11] or 1024'u64
    cptr[12] = cptr[12] or 32'u64
    v = cptr[13] or 1'u64
    v = v or 1'u64
    cptr[13] = v or 576460752303423488'u64
    cptr[14] = cptr[14] or 18014398509481984'u64
    cptr[15] = cptr[15] or 562949953421312'u64
    cptr[16] = cptr[16] or 17592186044416'u64
    cptr[17] = cptr[17] or 549755813888'u64
    cptr[18] = cptr[18] or 17179869184'u64
    cptr[19] = cptr[19] or 536870912'u64
    cptr[20] = cptr[20] or 16777216'u64
    cptr[21] = cptr[21] or 524288'u64
    cptr[22] = cptr[22] or 16384'u64
    cptr[23] = cptr[23] or 512'u64
    v = cptr[24] or 16'u64
    v = v or 16'u64
    cptr[24] = v or 9223372036854775808'u64
    cptr[25] = cptr[25] or 288230376151711744'u64
    cptr[26] = cptr[26] or 9007199254740992'u64
    cptr[27] = cptr[27] or 281474976710656'u64
    cptr[28] = cptr[28] or 8796093022208'u64
    cptr[29] = cptr[29] or 274877906944'u64
    cptr[30] = cptr[30] or 8589934592'u64
    cptr[31] = cptr[31] or 268435456'u64
    cptr[32] = cptr[32] or 8388608'u64
    cptr[33] = cptr[33] or 262144'u64
    cptr[34] = cptr[34] or 8192'u64
    cptr[35] = cptr[35] or 256'u64
    v = cptr[36] or 8'u64
    v = v or 8'u64
    cptr[36] = v or 4611686018427387904'u64
    cptr[37] = cptr[37] or 144115188075855872'u64
    cptr[38] = cptr[38] or 4503599627370496'u64
    cptr[39] = cptr[39] or 140737488355328'u64
    cptr[40] = cptr[40] or 4398046511104'u64
    cptr[41] = cptr[41] or 137438953472'u64
    cptr[42] = cptr[42] or 4294967296'u64
    cptr[43] = cptr[43] or 134217728'u64
    cptr[44] = cptr[44] or 4194304'u64
    cptr[45] = cptr[45] or 131072'u64
    cptr[46] = cptr[46] or 4096'u64
    cptr[47] = cptr[47] or 128'u64
    v = cptr[48] or 4'u64
    v = v or 4'u64
    cptr[48] = v or 2305843009213693952'u64
    cptr[49] = cptr[49] or 72057594037927936'u64
    cptr[50] = cptr[50] or 2251799813685248'u64
    cptr[51] = cptr[51] or 70368744177664'u64
    cptr[52] = cptr[52] or 2199023255552'u64
    cptr[53] = cptr[53] or 68719476736'u64
    cptr[54] = cptr[54] or 2147483648'u64
    cptr[55] = cptr[55] or 67108864'u64
    cptr[56] = cptr[56] or 2097152'u64
    cptr[57] = cptr[57] or 65536'u64
    cptr[58] = cptr[58] or 2048'u64
    cptr[59] = cptr[59] or 64'u64
    seta += adv
  ndx = ((seta - bitbufa) shl 3) or mod0.int
```
It's not rocket science; it is just using the compiler's capabilities to generate the modulo patterns including the literal/immediate `or`ing values in order to get the maximum speed.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
