### PR TITLE
Use built-in prime_list function in Euphoria

### PR DESCRIPTION
**Pull request by rzuckerm**
## Description
I've implemented an Euphoria solution using the built-in [prime_list function](https://openeuphoria.org/docs/std_primes.html#_4387_prime_list). It's pretty fast!

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Very interesting to see an implementation based on a prime calculation facility provided by the language's core library. I think that's actually a first for this project. 

I will need a little more time to be able to do a full review, but I did notice you labelling the algorithm as `unknown` in the benchmark output. The contributing guidelines for this project state that if the algorithm is not a confirmed case of `base` or `wheel`, the (only) other option is `other`. So I'd like to kindly ask you to already make that change.

**Comment by rbergen** [comment]
Haha, snap. Thanks!

**Comment by rzuckerm** [comment]
@rbergen I'm taking the PR back to draft mode. After analyzing the `prime_list` function, I see that it is using a global variable to store the answer. On the first call, it builds the answer. On subsequent calls it just returns the same answer. I'm going to see if there is a way to reset the global variable each time.

**Comment by rzuckerm** [comment]
@rbergen I'm closing this PR since there is no way to reset the global variable. The variable is private to `primes.e`. The only alternative would be to copy the function from the Euphoria library, and I didn't want to do that because I don't know if that will violate their licensing model. I may use it as a basis for my own trial division algorithm.

**Comment by rbergen** [comment]
@rzuckerm Thanks for your updates, and the thorough investigation into the inner workings of the `prime_list` function. As I said, I would have loved to include a solution that's based on a core library prime number identification routine, but I understand your conclusion concerning it.

That said, I took a look at the Euphoria license, and it's basically the MIT license. That's a very permissive one, which does allow you to use, modify and redistribute (parts of) the Euphoria source code, if you want to. I'm just noting this in case you still consider adding a trial division-based solution, later on.

**Comment by rzuckerm** [comment]
> That said, I took a look at the Euphoria license, and it's basically the MIT license. That's a very permissive one, which does allow you to use, modify and redistribute (parts of) the Euphoria source code, if you want to. I'm just noting this in case you still consider adding a trial division-based solution, later on.

Thanks @rbergen . I hadn't had time to research the licensing. I'm familiar with the MIT license. I'll do another pass at this using their code, and I might make some tweaks to it. For instance, there's no reason to yield to other tasks, and there's no reason to put a time limit on how long the primes calculation takes. Other than that, I'll try to stay true to the original implementation

**Pull request closed without merging**
