### PR TITLE
PrimePY: using array slicing

### PR DESCRIPTION
**Pull request by jannekotka**
Changed to use array slicing and numpy. Increases perf
by 20x

Signed-off-by: Janne Kotka <lekonna@gmail.com>

### CODE REVIEW

**Comment by jannekotka** [comment]
I have also one without numpy. keep the initialization as in the original and replace the for loop with 
this.rawbits[int(factor*3/2):this.sieveSize//2:factor] = [False] * len(this.rawbits[int(factor*3/2):this.sieveSize//2:factor])

**Comment by rhbvkleef** [comment]
I *think* that we can consider slicing faithful, but I am open to discussion.

**Comment by oscardssmith** [comment]
IMO, it might be a good idea to have separate python and python_numpy implementations.

**Comment by rbergen** [comment]
I would agree that slicing is faithful. However, we can't merge this PR until it is opened on the drag-race branch.

**Comment by rbergen** [comment]
Closing due to lack of contributor response. Can be reopened on drag-race branch if desired.

**Comment by rbergen** [comment]
Closing due to lack of contributor response. Can be reopened on drag-race branch if desired.

**Pull request closed without merging**
