### PR TITLE
Clojure solution 2

### PR DESCRIPTION
**Pull request by axvr**
## Description

Fast and faithful (but not quite idiomatic) Clojure solution.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

## Sample output

```
Passes: 6518, Time: 5.000845743, Avg: 7.672362E-4, Limit: 1000000, Count: 78498, Valid: True
axvr_clj-sln-2_8-bit;6518;5.000845743;1;algorithm=base,faithful=yes,bits=8
Passes: 3040, Time: 5.001040736, Avg: 0.0016450792, Limit: 1000000, Count: 78498, Valid: True
axvr_clj-sln-2_1-bit;3040;5.001040736;1;algorithm=base,faithful=yes,bits=1
```

(On an Intel Core i7-8550U @1.80GHz x8 CPU with 16GB of RAM using warm-up.)

### CODE REVIEW

**Comment by axvr** [comment]
I've force pushed an update which improved variable naming and added some explanatory comments.

**Comment by axvr** [comment]
Pushed change confirming boolean array bit usage as 8 bits/boolean.  Unfortunately this disqualifies it from the main leaderboard.  :(

**Comment by axvr** [comment]
Pushed final change to slightly improve performance further.  Should now be ready for review.

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by axvr** [comment]
@rbergen, I've re-requested review as I've pushed some new changes.
- Greatly improved the performance of solution 2
- Added solution 3 using a 1-bit data structure (but is half the speed of solution 2).

**Comment by axvr** [comment]
Also these solutions use a "warm-up" like the Java solution 4 does to reduce the variability of the results.  If this is not OK, I'm happy to disable/remove it.

**Comment by rbergen** [comment]
If you want to add a second approach, then please restructure this PR to one solution with two implementations.

**Review by rbergen — COMMENTED** [review]
If you want to add a second approach, then please restructure this PR to one solution with two implementations.

**Comment by rbergen** [comment]
> Also these solutions use a "warm-up" like the Java solution 4 does to reduce the variability of the results. If this is not OK, I'm happy to disable/remove it.

We've basically settled on condoning a warmup of a maximum of 5 seconds. In the case of multiple implementations within a solution, it's nice if the warmup time can be limited to a total of 5 seconds for all implementations combined. Also, we may revisit this decision when we implement a "best of n" benchmark setup, meaning we run every solution n times (5 is what we're now considering) and then report the result of the best-performing run.

**Comment by axvr** [comment]
Merged both solutions into the `solution_2` folder.   Only the 8-bit solution is using a warm-up.

I like the idea of a "best-of-n-runs" as a way to reduce results variability, although I'd imagine that it'll take n times longer to run all the benchmarks, so the 5 seconds maximum warm-up seems fair.

**Comment by rbergen** [comment]
> I like the idea of a "best-of-n-runs" as a way to reduce results variability, although I'd imagine that it'll take n times longer to run all the benchmarks.

It will indeed multiply the benchmark runtime with something close to n. One of the things we're considering is how to make this configurable (and what to make the default). Longer runtimes is less of a problem when it concerns scheduled jobs on more or less dedicated hardware, which is how the PrimeView reports are/will be generated. That is also where a reduction of variability is most relevant.

**Review by rbergen — APPROVED** [review]
LGTM

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
