### PR TITLE
TeX/solution_2 small improvement from systematic `=` in assignments

### PR DESCRIPTION
**Pull request by jfbu**
## Description

Small speed improvement from using systematically `=` in dimen and count assignments.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
This is your second PR on the same solution within 13 hours. Are you planning to do more work on it? If so, I would like to ask you to please consolidate your changes in one PR.

**Comment by jfbu** [comment]
@rbergen I actually (unexpectedly to me) do. There is some small improvement which I had rejected last week as not really significant but on isolating it I found only now it is unquestionably a faster syntax. I expect to be done in less than one hour from now. My intention is that this should be last change. Once done I will request your review.

**Comment by jfbu** [comment]
Sorry for delay. I am done now (for good).

**Comment by jfbu** [comment]
@rbergen I was planning to "request a review" from you but it appears I don't have the access rights...  or I too dumb to find the corresponding icon. Thanks to you and other maintainers for all the work going into supervising all of this.

**Pull request merged**
