### PR TITLE
[Java] Update Java to Java 16

### PR DESCRIPTION
**Pull request by gamlerhart**
## Description
Java 16 is the latest release. Upgrade to Java solutions to Java 16.
Seem to give a performance bump, especially the boolean[] implementation.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
Tagging @MansenC and @PratimGhosh86 and allowing time for them to review and respond to this PR on their original solutions, if they want to do so.

**Comment by rbergen** [comment]
@gamlerhart Can you provide some numbers on the performance improvements you've witnessed?

**Comment by gamlerhart** [comment]
@rbergen Of course.

On my dev machine with a Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz CPU.

Solution 1 on Java 11: Around 4900 passes.
    
    roman@roman-mibex ~/d/p/P/P/solution_1 (update-java-to-java-16)> docker run --rm mes
    Passes: 4823, Time: 5.000000, Avg: 0.001037, Limit: 1000000, Count: 78498, Valid: true

    MansenC;4823;5.000000;1;algorithm=base,faithful=yes
    roman@roman-mibex ~/d/p/P/P/solution_1 (update-java-to-java-16)> docker run --rm mes
    Passes: 4904, Time: 5.000000, Avg: 0.001020, Limit: 1000000, Count: 78498, Valid: true

    MansenC;4904;5.000000;1;algorithm=base,faithful=yes
    roman@roman-mibex ~/d/p/P/P/solution_1 (update-java-to-java-16)> docker run --rm mes
    Passes: 4839, Time: 5.000000, Avg: 0.001033, Limit: 1000000, Count: 78498, Valid: true

    MansenC;4839;5.000000;1;algorithm=base,faithful=yes


Solution 1 on Java 16: Around 5700 passes:

    roman@roman-mibex ~/d/p/P/P/solution_1 (update-java-to-java-16)> docker run --rm mes
    Passes: 5717, Time: 5.000000, Avg: 0.000875, Limit: 1000000, Count: 78498, Valid: true

    MansenC;5717;5.000000;1;algorithm=base,faithful=yes
    roman@roman-mibex ~/d/p/P/P/solution_1 (update-java-to-java-16)> docker run --rm mes
    Passes: 5678, Time: 5.000000, Avg: 0.000881, Limit: 1000000, Count: 78498, Valid: true

    MansenC;5678;5.000000;1;algorithm=base,faithful=yes
    roman@roman-mibex ~/d/p/P/P/solution_1 (update-java-to-java-16)> docker run --rm mes
    Passes: 5601, Time: 5.000000, Avg: 0.000893, Limit: 1000000, Count: 78498, Valid: true

    MansenC;5601;5.000000;1;algorithm=base,faithful=yes
    
 For Solution 2 the difference isn't as clear.
 
 Solution 2 on Java  11: around 2700 passes:
 
    roman@roman-mibex ~/d/p/P/P/solution_2 (update-java-to-java-16)> docker run --rm mes
    Passes: 2696, Time: 5.000000, Avg: 0.001855, Limit: 1000000, Count: 78498, Valid: true

    PratimGhosh86;2696;5.000000;1;algorithm=base,faithful=yes,bits=1
    roman@roman-mibex ~/d/p/P/P/solution_2 (update-java-to-java-16)> docker run --rm mes
    Passes: 2700, Time: 5.000000, Avg: 0.001852, Limit: 1000000, Count: 78498, Valid: true

    PratimGhosh86;2700;5.000000;1;algorithm=base,faithful=yes,bits=1
    roman@roman-mibex ~/d/p/P/P/solution_2 (update-java-to-java-16)> docker run --rm mes
    Passes: 2621, Time: 5.000000, Avg: 0.001908, Limit: 1000000, Count: 78498, Valid: true

    PratimGhosh86;2621;5.000000;1;algorithm=base,faithful=yes,bits=1
    
 Solution 2 on Java 16: around 2850 passes:
 
    
    roman@roman-mibex ~/d/p/P/P/solution_2 (update-java-to-java-16)> docker run --rm mes
    Passes: 2944, Time: 5.000000, Avg: 0.001698, Limit: 1000000, Count: 78498, Valid: true

    PratimGhosh86;2944;5.000000;1;algorithm=base,faithful=yes,bits=1
    roman@roman-mibex ~/d/p/P/P/solution_2 (update-java-to-java-16)> docker run --rm mes
    Passes: 2852, Time: 5.000000, Avg: 0.001753, Limit: 1000000, Count: 78498, Valid: true

    PratimGhosh86;2852;5.000000;1;algorithm=base,faithful=yes,bits=1
    roman@roman-mibex ~/d/p/P/P/solution_2 (update-java-to-java-16)> docker run --rm mes
    Passes: 2876, Time: 5.000000, Avg: 0.001739, Limit: 1000000, Count: 78498, Valid: true

    PratimGhosh86;2876;5.000000;1;algorithm=base,faithful=yes,bits=1

**Comment by rbergen** [comment]
@gamlerhart Thank you. I've done some desk research (aka Googling), and that also yields consistent reports that JDK15/16 is indeed faster than JDK11. Based on that and your numbers, I'm going to merge this.

**Pull request merged**
