### PR TITLE
PrimePowershell

### PR DESCRIPTION
**Pull request by justusiv**
Basics of a powershell script to find primes. I did not include the timer.

### CODE REVIEW

**Comment by pepper-lees** [comment]
Couldn't you implement a timer with this? https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=netframework-4.7.2

```powershell
$StartTime = Get-Date
# do stuff

  # inside your loop
  $Interval = Get-Date - $StartTime 
  # compare Interval.TotalSeconds
```

**Comment by justusiv** [comment]
> Couldn't you implement a timer with this? https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=netframework-4.7.2
> 
> ```powershell
> $StartTime = Get-Date
> # do stuff
> 
>   # inside your loop
>   $Interval = Get-Date - $StartTime 
>   # compare Interval.TotalSeconds
> ```

Yeah i typically do that for timing things. This code didn't really fit into the category of how many times in 5 seconds so I scrapped it all together. I am no expert just some guy in a basement so i'm sure there are many language optimizations that could help out. I would love to see it. I did leave a tiny bit of debug code in which slows it down i'm sure but not enough to matter.

**Comment by rbergen** [comment]
We now have two PowerShell solutions in the drag-race branch, both of which include a timer. We could add another PowerShell solution, but it would have to comply with the [contributing guidelines](https://github.com/PlummersSoftwareLLC/Primes/blob/drag-race/CONTRIBUTING.md) and differ from the existing solutions in a meaningful way. This means that the solution does need to be timed, and the PR would need to be opened on the "drag-race" branch, not on "original" (formerly "main").

**Comment by rbergen** [comment]
Closing this due to alternative PowerShell solutions being in place.

**Pull request closed without merging**
