### PR TITLE
Pascal Solution 3

### PR DESCRIPTION
**Pull request by olivierbrun**
## Description

This is a multithreaded implementation of the base algorithm written in freepascal (packed bits to flag prime numbers, faithful, 64 bits integer for primes). The class along with the memory buffer storing the bits are destroyed after each pass.
Added command line options providing the ability to specify the number of threads, the duration, and the sieve size.
Default values if no parameter is specified are: duration: 5, sieve size: 1000000, threads count: number of cpu cores available on the system.

## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
In the future, please make your commit messages more descriptive. You could probably just use the "extended description" you now set as the main message, in most cases. 

Also, please let me know when this PR is stable.

**Comment by olivierbrun** [comment]
hello Rutger, thanks for the suggestion, 

I'll use the extended description in the commit message from now on. This PR is stable, no more update to add in the short term.

**Comment by olivierbrun** [comment]
@rbergen 
hello Rutger, this PR is stable. Please let me know if any additional action is needed on my end.

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by olivierbrun** [comment]
Wonderful, thanks so much Rutger.

**Review by marghidanu — APPROVED** [review]

**Pull request merged**
