### PR TITLE
Add Minecraft Datapack solution

### PR DESCRIPTION
**Pull request by RCoder01**
## Description

Adds a solution using the Minecraft datapack format to run inside a Minecraft server. Run instructions are included in the Readme.
## Contributing requirements

* [x] I read the contribution guidelines in CONTRIBUTING.md.
* [x] I placed my solution in the correct solution folder.
* [x] I added a README.md with the right badge(s).
* [x] I added a Dockerfile that builds and runs my solution.
* [x] I selected `drag-race` as the target branch.
* [x] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Review by rbergen — APPROVED** [review]
LGTM

**Comment by Macleykun** [comment]
Just wanted to ask, are these line endings ok to be merged?
[image](https://github.com/PlummersSoftwareLLC/Primes/blob/1317fc19c439801d8a658c75e07334729eeb20f4/PrimeMinecraftDatapack/solution_1/Pack/data/sieve/functions/calculate.mcfunction) <-clickable

**Comment by rbergen** [comment]
The solution works with them in, so yes.

**Comment by RCoder01** [comment]
I'm not too sure what those line ends are; I didn't intend for them to be there, but as rbergen said, it works with them.

**Comment by Macleykun** [comment]
> I'm not too sure what those line ends are; I didn't intend for them to be there, but as rbergen said, it works with them.

It's only that t he file endings are in the Windows format CR+LF) and not in the Unix format (LF).

I'll just place it here incase you would change your mind, aslong as CI is all green, all is good :-)
[Source](https://askubuntu.com/questions/803162/how-to-change-windows-line-ending-to-unix-version)

A (tested) way is: `find ./Primes/PrimeMinecraftDatapack/solution_1 -type f -print0 | xargs -0 sed -i 's/\r$//g' --`
Which is a mix of two solutions to recursively do it for all files.

Proof:
```
macley@bitterbal:~/test/Primes/PrimeMinecraftDatapack/solution_1$ file server.properties
server.properties: ASCII text, with CRLF line terminators
macley@bitterbal:~/test/Primes/PrimeMinecraftDatapack/solution_1$ cd ../../../
macley@bitterbal:~/test$ find ./Primes/PrimeMinecraftDatapack/solution_1 -type f -print0 | xargs -0 sed -i 's/\r$//g' --
macley@bitterbal:~/test$ file ./Primes/PrimeMinecraftDatapack/solution_1/server.properties
./Primes/PrimeMinecraftDatapack/solution_1/server.properties: ASCII text
```
[Source](https://stackoverflow.com/a/3570574)

As you two said, the solution works, so it isn't needed to be fixed :)

**Comment by rbergen** [comment]
CI doesn't actually build this solution for licensing reasons, but I've successfully built and run the solution locally, using Docker, the solution's build and run scripts and manually.
And indeed, for some reason GitHub just seems to rather noisily mark the CR part of the CRLF line ends in the .mcfunction files.

**Comment by Macleykun** [comment]
> CI doesn't actually build this solution for licensing reasons, but I've successfully built and run the solution locally, using Docker, the solution's build and run scripts and manually. And indeed, for some reason GitHub just seems to rather noisily mark the CR part of the CRLF line ends in the .mcfunction files.

Sorry, i meant to say that if CI works, then indeed no matter the file ending it's all good!

**Review by marghidanu — APPROVED** [review]

**Comment by marghidanu** [comment]
Nice work guys!

**Pull request merged**
