### PR TITLE
C# bitsperprime consistency

### PR DESCRIPTION
**Pull request by dmannock**
## Description
Added missing bitsperprime on some implementations using BitArray so they are consistent. As mentioned in PR #283.

## Contributing requirements

* [X] I read the contribution guidelines in CONTRIBUTING.md.
* [X] I placed my solution in the correct solution folder.
* [X] I added a README.md with the right badge(s).
* [X] I added a Dockerfile that builds and runs my solution.
* [X] I selected `drag-race` as the target branch.
* [X] All code herein is licensed compatible with BSD-3.

### CODE REVIEW

**Comment by rbergen** [comment]
The reason I didn't include the implementations in the Benchmark directory under CSharp/solution_1 when drafting #219 is that they are not used by the drag race benchmark run; those are all in the Sieves directory. I tend to limit drag-race driven conformity changes that I implement to the minimum that is required to make existing solutions conform. 

That said, I'm tagging @Kinematics to review and comment on this PR if they want to.

**Comment by dmannock** [comment]
Fair enough. Main reason I noticed is when running with --all the 'bits=1' wasn't shown on the original sieve version:

```
@Kinematics: Starting (original)...
Passes: 2677, Time: 5.00053 s, Per Loop: 1.867762 ms, Sieve Size: 1000000, Thread Count: 1, Primes Found: 78498, Valid: True
kinematics_original;2677;5.00053;1;algorithm=base,faithful=yes

@Kinematics: Starting (standard)...
Passes: 3673, Time: 5.00067 s, Per Loop: 1.361285 ms, Sieve Size: 1000000, Thread Count: 1, Primes Found: 78498, Valid: True
kinematics_standard;3673;5.00067;1;algorithm=base,faithful=yes,bits=1
```

Good stuff, cheers for the assistance!

**Comment by Kinematics** [comment]
I don't see any issues with it.

**Comment by rbergen** [comment]
Merging with original author's approval.

**Pull request merged**
